/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: IVI_Tbox_V2.0.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "tbox_ivi_pb.h"
void   tbox__net__call_action__init
                     (Tbox__Net__CallAction         *message)
{
  static const Tbox__Net__CallAction init_value = TBOX__NET__CALL_ACTION__INIT;
  *message = init_value;
}
size_t tbox__net__call_action__get_packed_size
                     (const Tbox__Net__CallAction *message)
{
  assert(message->base.descriptor == &tbox__net__call_action__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__call_action__pack
                     (const Tbox__Net__CallAction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__call_action__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__call_action__pack_to_buffer
                     (const Tbox__Net__CallAction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__call_action__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__CallAction *
       tbox__net__call_action__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__CallAction *)
     protobuf_c_message_unpack (&tbox__net__call_action__descriptor,
                                allocator, len, data);
}
void   tbox__net__call_action__free_unpacked
                     (Tbox__Net__CallAction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__call_action__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__call_action_result__init
                     (Tbox__Net__CallActionResult         *message)
{
  static const Tbox__Net__CallActionResult init_value = TBOX__NET__CALL_ACTION_RESULT__INIT;
  *message = init_value;
}
size_t tbox__net__call_action_result__get_packed_size
                     (const Tbox__Net__CallActionResult *message)
{
  assert(message->base.descriptor == &tbox__net__call_action_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__call_action_result__pack
                     (const Tbox__Net__CallActionResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__call_action_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__call_action_result__pack_to_buffer
                     (const Tbox__Net__CallActionResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__call_action_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__CallActionResult *
       tbox__net__call_action_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__CallActionResult *)
     protobuf_c_message_unpack (&tbox__net__call_action_result__descriptor,
                                allocator, len, data);
}
void   tbox__net__call_action_result__free_unpacked
                     (Tbox__Net__CallActionResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__call_action_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__call_status__init
                     (Tbox__Net__CallStatus         *message)
{
  static const Tbox__Net__CallStatus init_value = TBOX__NET__CALL_STATUS__INIT;
  *message = init_value;
}
size_t tbox__net__call_status__get_packed_size
                     (const Tbox__Net__CallStatus *message)
{
  assert(message->base.descriptor == &tbox__net__call_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__call_status__pack
                     (const Tbox__Net__CallStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__call_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__call_status__pack_to_buffer
                     (const Tbox__Net__CallStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__call_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__CallStatus *
       tbox__net__call_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__CallStatus *)
     protobuf_c_message_unpack (&tbox__net__call_status__descriptor,
                                allocator, len, data);
}
void   tbox__net__call_status__free_unpacked
                     (Tbox__Net__CallStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__call_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__tbox_info__init
                     (Tbox__Net__TboxInfo         *message)
{
  static const Tbox__Net__TboxInfo init_value = TBOX__NET__TBOX_INFO__INIT;
  *message = init_value;
}
size_t tbox__net__tbox_info__get_packed_size
                     (const Tbox__Net__TboxInfo *message)
{
  assert(message->base.descriptor == &tbox__net__tbox_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__tbox_info__pack
                     (const Tbox__Net__TboxInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__tbox_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__tbox_info__pack_to_buffer
                     (const Tbox__Net__TboxInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__tbox_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__TboxInfo *
       tbox__net__tbox_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__TboxInfo *)
     protobuf_c_message_unpack (&tbox__net__tbox_info__descriptor,
                                allocator, len, data);
}
void   tbox__net__tbox_info__free_unpacked
                     (Tbox__Net__TboxInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__tbox_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__tbox_gpscmd__init
                     (Tbox__Net__TboxGPSCmd         *message)
{
  static const Tbox__Net__TboxGPSCmd init_value = TBOX__NET__TBOX_GPSCMD__INIT;
  *message = init_value;
}
size_t tbox__net__tbox_gpscmd__get_packed_size
                     (const Tbox__Net__TboxGPSCmd *message)
{
  assert(message->base.descriptor == &tbox__net__tbox_gpscmd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__tbox_gpscmd__pack
                     (const Tbox__Net__TboxGPSCmd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__tbox_gpscmd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__tbox_gpscmd__pack_to_buffer
                     (const Tbox__Net__TboxGPSCmd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__tbox_gpscmd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__TboxGPSCmd *
       tbox__net__tbox_gpscmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__TboxGPSCmd *)
     protobuf_c_message_unpack (&tbox__net__tbox_gpscmd__descriptor,
                                allocator, len, data);
}
void   tbox__net__tbox_gpscmd__free_unpacked
                     (Tbox__Net__TboxGPSCmd *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__tbox_gpscmd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__tbox_gpsinfo__init
                     (Tbox__Net__TboxGPSInfo         *message)
{
  static const Tbox__Net__TboxGPSInfo init_value = TBOX__NET__TBOX_GPSINFO__INIT;
  *message = init_value;
}
size_t tbox__net__tbox_gpsinfo__get_packed_size
                     (const Tbox__Net__TboxGPSInfo *message)
{
  assert(message->base.descriptor == &tbox__net__tbox_gpsinfo__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__tbox_gpsinfo__pack
                     (const Tbox__Net__TboxGPSInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__tbox_gpsinfo__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__tbox_gpsinfo__pack_to_buffer
                     (const Tbox__Net__TboxGPSInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__tbox_gpsinfo__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__TboxGPSInfo *
       tbox__net__tbox_gpsinfo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__TboxGPSInfo *)
     protobuf_c_message_unpack (&tbox__net__tbox_gpsinfo__descriptor,
                                allocator, len, data);
}
void   tbox__net__tbox_gpsinfo__free_unpacked
                     (Tbox__Net__TboxGPSInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__tbox_gpsinfo__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__tbox_wifi_client_info__init
                     (Tbox__Net__TboxWifiClientInfo         *message)
{
  static const Tbox__Net__TboxWifiClientInfo init_value = TBOX__NET__TBOX_WIFI_CLIENT_INFO__INIT;
  *message = init_value;
}
size_t tbox__net__tbox_wifi_client_info__get_packed_size
                     (const Tbox__Net__TboxWifiClientInfo *message)
{
  assert(message->base.descriptor == &tbox__net__tbox_wifi_client_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__tbox_wifi_client_info__pack
                     (const Tbox__Net__TboxWifiClientInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__tbox_wifi_client_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__tbox_wifi_client_info__pack_to_buffer
                     (const Tbox__Net__TboxWifiClientInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__tbox_wifi_client_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__TboxWifiClientInfo *
       tbox__net__tbox_wifi_client_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__TboxWifiClientInfo *)
     protobuf_c_message_unpack (&tbox__net__tbox_wifi_client_info__descriptor,
                                allocator, len, data);
}
void   tbox__net__tbox_wifi_client_info__free_unpacked
                     (Tbox__Net__TboxWifiClientInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__tbox_wifi_client_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__wifi_status__init
                     (Tbox__Net__WifiStatus         *message)
{
  static const Tbox__Net__WifiStatus init_value = TBOX__NET__WIFI_STATUS__INIT;
  *message = init_value;
}
size_t tbox__net__wifi_status__get_packed_size
                     (const Tbox__Net__WifiStatus *message)
{
  assert(message->base.descriptor == &tbox__net__wifi_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__wifi_status__pack
                     (const Tbox__Net__WifiStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__wifi_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__wifi_status__pack_to_buffer
                     (const Tbox__Net__WifiStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__wifi_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__WifiStatus *
       tbox__net__wifi_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__WifiStatus *)
     protobuf_c_message_unpack (&tbox__net__wifi_status__descriptor,
                                allocator, len, data);
}
void   tbox__net__wifi_status__free_unpacked
                     (Tbox__Net__WifiStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__wifi_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__wifi_set_cmd__init
                     (Tbox__Net__WifiSetCmd         *message)
{
  static const Tbox__Net__WifiSetCmd init_value = TBOX__NET__WIFI_SET_CMD__INIT;
  *message = init_value;
}
size_t tbox__net__wifi_set_cmd__get_packed_size
                     (const Tbox__Net__WifiSetCmd *message)
{
  assert(message->base.descriptor == &tbox__net__wifi_set_cmd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__wifi_set_cmd__pack
                     (const Tbox__Net__WifiSetCmd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__wifi_set_cmd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__wifi_set_cmd__pack_to_buffer
                     (const Tbox__Net__WifiSetCmd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__wifi_set_cmd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__WifiSetCmd *
       tbox__net__wifi_set_cmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__WifiSetCmd *)
     protobuf_c_message_unpack (&tbox__net__wifi_set_cmd__descriptor,
                                allocator, len, data);
}
void   tbox__net__wifi_set_cmd__free_unpacked
                     (Tbox__Net__WifiSetCmd *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__wifi_set_cmd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__wifi_set_result__init
                     (Tbox__Net__WifiSetResult         *message)
{
  static const Tbox__Net__WifiSetResult init_value = TBOX__NET__WIFI_SET_RESULT__INIT;
  *message = init_value;
}
size_t tbox__net__wifi_set_result__get_packed_size
                     (const Tbox__Net__WifiSetResult *message)
{
  assert(message->base.descriptor == &tbox__net__wifi_set_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__wifi_set_result__pack
                     (const Tbox__Net__WifiSetResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__wifi_set_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__wifi_set_result__pack_to_buffer
                     (const Tbox__Net__WifiSetResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__wifi_set_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__WifiSetResult *
       tbox__net__wifi_set_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__WifiSetResult *)
     protobuf_c_message_unpack (&tbox__net__wifi_set_result__descriptor,
                                allocator, len, data);
}
void   tbox__net__wifi_set_result__free_unpacked
                     (Tbox__Net__WifiSetResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__wifi_set_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__client_hello__init
                     (Tbox__Net__ClientHello         *message)
{
  static const Tbox__Net__ClientHello init_value = TBOX__NET__CLIENT_HELLO__INIT;
  *message = init_value;
}
size_t tbox__net__client_hello__get_packed_size
                     (const Tbox__Net__ClientHello *message)
{
  assert(message->base.descriptor == &tbox__net__client_hello__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__client_hello__pack
                     (const Tbox__Net__ClientHello *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__client_hello__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__client_hello__pack_to_buffer
                     (const Tbox__Net__ClientHello *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__client_hello__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__ClientHello *
       tbox__net__client_hello__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__ClientHello *)
     protobuf_c_message_unpack (&tbox__net__client_hello__descriptor,
                                allocator, len, data);
}
void   tbox__net__client_hello__free_unpacked
                     (Tbox__Net__ClientHello *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__client_hello__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__client_send_certificate__init
                     (Tbox__Net__ClientSendCertificate         *message)
{
  static const Tbox__Net__ClientSendCertificate init_value = TBOX__NET__CLIENT_SEND_CERTIFICATE__INIT;
  *message = init_value;
}
size_t tbox__net__client_send_certificate__get_packed_size
                     (const Tbox__Net__ClientSendCertificate *message)
{
  assert(message->base.descriptor == &tbox__net__client_send_certificate__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__client_send_certificate__pack
                     (const Tbox__Net__ClientSendCertificate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__client_send_certificate__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__client_send_certificate__pack_to_buffer
                     (const Tbox__Net__ClientSendCertificate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__client_send_certificate__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__ClientSendCertificate *
       tbox__net__client_send_certificate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__ClientSendCertificate *)
     protobuf_c_message_unpack (&tbox__net__client_send_certificate__descriptor,
                                allocator, len, data);
}
void   tbox__net__client_send_certificate__free_unpacked
                     (Tbox__Net__ClientSendCertificate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__client_send_certificate__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__client_finish__init
                     (Tbox__Net__ClientFinish         *message)
{
  static const Tbox__Net__ClientFinish init_value = TBOX__NET__CLIENT_FINISH__INIT;
  *message = init_value;
}
size_t tbox__net__client_finish__get_packed_size
                     (const Tbox__Net__ClientFinish *message)
{
  assert(message->base.descriptor == &tbox__net__client_finish__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__client_finish__pack
                     (const Tbox__Net__ClientFinish *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__client_finish__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__client_finish__pack_to_buffer
                     (const Tbox__Net__ClientFinish *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__client_finish__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__ClientFinish *
       tbox__net__client_finish__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__ClientFinish *)
     protobuf_c_message_unpack (&tbox__net__client_finish__descriptor,
                                allocator, len, data);
}
void   tbox__net__client_finish__free_unpacked
                     (Tbox__Net__ClientFinish *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__client_finish__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__certification_step__init
                     (Tbox__Net__CertificationStep         *message)
{
  static const Tbox__Net__CertificationStep init_value = TBOX__NET__CERTIFICATION_STEP__INIT;
  *message = init_value;
}
size_t tbox__net__certification_step__get_packed_size
                     (const Tbox__Net__CertificationStep *message)
{
  assert(message->base.descriptor == &tbox__net__certification_step__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__certification_step__pack
                     (const Tbox__Net__CertificationStep *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__certification_step__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__certification_step__pack_to_buffer
                     (const Tbox__Net__CertificationStep *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__certification_step__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__CertificationStep *
       tbox__net__certification_step__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__CertificationStep *)
     protobuf_c_message_unpack (&tbox__net__certification_step__descriptor,
                                allocator, len, data);
}
void   tbox__net__certification_step__free_unpacked
                     (Tbox__Net__CertificationStep *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__certification_step__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__certification_cmd__init
                     (Tbox__Net__CertificationCmd         *message)
{
  static const Tbox__Net__CertificationCmd init_value = TBOX__NET__CERTIFICATION_CMD__INIT;
  *message = init_value;
}
size_t tbox__net__certification_cmd__get_packed_size
                     (const Tbox__Net__CertificationCmd *message)
{
  assert(message->base.descriptor == &tbox__net__certification_cmd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__certification_cmd__pack
                     (const Tbox__Net__CertificationCmd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__certification_cmd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__certification_cmd__pack_to_buffer
                     (const Tbox__Net__CertificationCmd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__certification_cmd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__CertificationCmd *
       tbox__net__certification_cmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__CertificationCmd *)
     protobuf_c_message_unpack (&tbox__net__certification_cmd__descriptor,
                                allocator, len, data);
}
void   tbox__net__certification_cmd__free_unpacked
                     (Tbox__Net__CertificationCmd *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__certification_cmd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__server_send_certificate__init
                     (Tbox__Net__ServerSendCertificate         *message)
{
  static const Tbox__Net__ServerSendCertificate init_value = TBOX__NET__SERVER_SEND_CERTIFICATE__INIT;
  *message = init_value;
}
size_t tbox__net__server_send_certificate__get_packed_size
                     (const Tbox__Net__ServerSendCertificate *message)
{
  assert(message->base.descriptor == &tbox__net__server_send_certificate__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__server_send_certificate__pack
                     (const Tbox__Net__ServerSendCertificate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__server_send_certificate__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__server_send_certificate__pack_to_buffer
                     (const Tbox__Net__ServerSendCertificate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__server_send_certificate__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__ServerSendCertificate *
       tbox__net__server_send_certificate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__ServerSendCertificate *)
     protobuf_c_message_unpack (&tbox__net__server_send_certificate__descriptor,
                                allocator, len, data);
}
void   tbox__net__server_send_certificate__free_unpacked
                     (Tbox__Net__ServerSendCertificate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__server_send_certificate__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__server_finish__init
                     (Tbox__Net__ServerFinish         *message)
{
  static const Tbox__Net__ServerFinish init_value = TBOX__NET__SERVER_FINISH__INIT;
  *message = init_value;
}
size_t tbox__net__server_finish__get_packed_size
                     (const Tbox__Net__ServerFinish *message)
{
  assert(message->base.descriptor == &tbox__net__server_finish__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__server_finish__pack
                     (const Tbox__Net__ServerFinish *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__server_finish__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__server_finish__pack_to_buffer
                     (const Tbox__Net__ServerFinish *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__server_finish__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__ServerFinish *
       tbox__net__server_finish__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__ServerFinish *)
     protobuf_c_message_unpack (&tbox__net__server_finish__descriptor,
                                allocator, len, data);
}
void   tbox__net__server_finish__free_unpacked
                     (Tbox__Net__ServerFinish *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__server_finish__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__certification_status__init
                     (Tbox__Net__CertificationStatus         *message)
{
  static const Tbox__Net__CertificationStatus init_value = TBOX__NET__CERTIFICATION_STATUS__INIT;
  *message = init_value;
}
size_t tbox__net__certification_status__get_packed_size
                     (const Tbox__Net__CertificationStatus *message)
{
  assert(message->base.descriptor == &tbox__net__certification_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__certification_status__pack
                     (const Tbox__Net__CertificationStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__certification_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__certification_status__pack_to_buffer
                     (const Tbox__Net__CertificationStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__certification_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__CertificationStatus *
       tbox__net__certification_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__CertificationStatus *)
     protobuf_c_message_unpack (&tbox__net__certification_status__descriptor,
                                allocator, len, data);
}
void   tbox__net__certification_status__free_unpacked
                     (Tbox__Net__CertificationStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__certification_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__certification_result__init
                     (Tbox__Net__CertificationResult         *message)
{
  static const Tbox__Net__CertificationResult init_value = TBOX__NET__CERTIFICATION_RESULT__INIT;
  *message = init_value;
}
size_t tbox__net__certification_result__get_packed_size
                     (const Tbox__Net__CertificationResult *message)
{
  assert(message->base.descriptor == &tbox__net__certification_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__certification_result__pack
                     (const Tbox__Net__CertificationResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__certification_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__certification_result__pack_to_buffer
                     (const Tbox__Net__CertificationResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__certification_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__CertificationResult *
       tbox__net__certification_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__CertificationResult *)
     protobuf_c_message_unpack (&tbox__net__certification_result__descriptor,
                                allocator, len, data);
}
void   tbox__net__certification_result__free_unpacked
                     (Tbox__Net__CertificationResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__certification_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__msg_result__init
                     (Tbox__Net__MsgResult         *message)
{
  static const Tbox__Net__MsgResult init_value = TBOX__NET__MSG_RESULT__INIT;
  *message = init_value;
}
size_t tbox__net__msg_result__get_packed_size
                     (const Tbox__Net__MsgResult *message)
{
  assert(message->base.descriptor == &tbox__net__msg_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__msg_result__pack
                     (const Tbox__Net__MsgResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__msg_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__msg_result__pack_to_buffer
                     (const Tbox__Net__MsgResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__msg_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__MsgResult *
       tbox__net__msg_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__MsgResult *)
     protobuf_c_message_unpack (&tbox__net__msg_result__descriptor,
                                allocator, len, data);
}
void   tbox__net__msg_result__free_unpacked
                     (Tbox__Net__MsgResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__msg_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__top_message__init
                     (Tbox__Net__TopMessage         *message)
{
  static const Tbox__Net__TopMessage init_value = TBOX__NET__TOP_MESSAGE__INIT;
  *message = init_value;
}
size_t tbox__net__top_message__get_packed_size
                     (const Tbox__Net__TopMessage *message)
{
  assert(message->base.descriptor == &tbox__net__top_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__top_message__pack
                     (const Tbox__Net__TopMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__top_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__top_message__pack_to_buffer
                     (const Tbox__Net__TopMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__top_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__TopMessage *
       tbox__net__top_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__TopMessage *)
     protobuf_c_message_unpack (&tbox__net__top_message__descriptor,
                                allocator, len, data);
}
void   tbox__net__top_message__free_unpacked
                     (Tbox__Net__TopMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tbox__net__top_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor tbox__net__call_action__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CallAction, type),
    &tbox__net__call_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CallAction, action),
    &tbox__net__call_action_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__call_action__field_indices_by_name[] = {
  1,   /* field[1] = action */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange tbox__net__call_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tbox__net__call_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.CallAction",
  "CallAction",
  "Tbox__Net__CallAction",
  "tbox.net",
  sizeof(Tbox__Net__CallAction),
  2,
  tbox__net__call_action__field_descriptors,
  tbox__net__call_action__field_indices_by_name,
  1,  tbox__net__call_action__number_ranges,
  (ProtobufCMessageInit) tbox__net__call_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__call_action_result__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CallActionResult, type),
    &tbox__net__call_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CallActionResult, action),
    &tbox__net__call_action_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CallActionResult, result),
    &tbox__net__call_action_result_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__call_action_result__field_indices_by_name[] = {
  1,   /* field[1] = action */
  2,   /* field[2] = result */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange tbox__net__call_action_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tbox__net__call_action_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.CallActionResult",
  "CallActionResult",
  "Tbox__Net__CallActionResult",
  "tbox.net",
  sizeof(Tbox__Net__CallActionResult),
  3,
  tbox__net__call_action_result__field_descriptors,
  tbox__net__call_action_result__field_indices_by_name,
  1,  tbox__net__call_action_result__number_ranges,
  (ProtobufCMessageInit) tbox__net__call_action_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__call_status__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CallStatus, type),
    &tbox__net__call_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call_status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CallStatus, call_status),
    &tbox__net__call_status_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reserve",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CallStatus, reserve),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__call_status__field_indices_by_name[] = {
  1,   /* field[1] = call_status */
  2,   /* field[2] = reserve */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange tbox__net__call_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tbox__net__call_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.CallStatus",
  "CallStatus",
  "Tbox__Net__CallStatus",
  "tbox.net",
  sizeof(Tbox__Net__CallStatus),
  3,
  tbox__net__call_status__field_descriptors,
  tbox__net__call_status__field_indices_by_name,
  1,  tbox__net__call_status__number_ranges,
  (ProtobufCMessageInit) tbox__net__call_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__tbox_info__field_descriptors[6] =
{
  {
    "software_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxInfo, software_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hardware_version",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxInfo, hardware_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iccid",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxInfo, iccid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pdid",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxInfo, pdid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imei",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxInfo, imei),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vin",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxInfo, vin),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__tbox_info__field_indices_by_name[] = {
  1,   /* field[1] = hardware_version */
  2,   /* field[2] = iccid */
  4,   /* field[4] = imei */
  3,   /* field[3] = pdid */
  0,   /* field[0] = software_version */
  5,   /* field[5] = vin */
};
static const ProtobufCIntRange tbox__net__tbox_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor tbox__net__tbox_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.TboxInfo",
  "TboxInfo",
  "Tbox__Net__TboxInfo",
  "tbox.net",
  sizeof(Tbox__Net__TboxInfo),
  6,
  tbox__net__tbox_info__field_descriptors,
  tbox__net__tbox_info__field_indices_by_name,
  1,  tbox__net__tbox_info__number_ranges,
  (ProtobufCMessageInit) tbox__net__tbox_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__tbox_gpscmd__field_descriptors[2] =
{
  {
    "onoff",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxGPSCmd, onoff),
    &tbox__net__gps__send__on_off__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_cycle",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxGPSCmd, time_cycle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__tbox_gpscmd__field_indices_by_name[] = {
  0,   /* field[0] = onoff */
  1,   /* field[1] = time_cycle */
};
static const ProtobufCIntRange tbox__net__tbox_gpscmd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tbox__net__tbox_gpscmd__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.TboxGPSCmd",
  "TboxGPSCmd",
  "Tbox__Net__TboxGPSCmd",
  "tbox.net",
  sizeof(Tbox__Net__TboxGPSCmd),
  2,
  tbox__net__tbox_gpscmd__field_descriptors,
  tbox__net__tbox_gpscmd__field_indices_by_name,
  1,  tbox__net__tbox_gpscmd__number_ranges,
  (ProtobufCMessageInit) tbox__net__tbox_gpscmd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__tbox_gpsinfo__field_descriptors[1] =
{
  {
    "nmea",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxGPSInfo, nmea),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__tbox_gpsinfo__field_indices_by_name[] = {
  0,   /* field[0] = nmea */
};
static const ProtobufCIntRange tbox__net__tbox_gpsinfo__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tbox__net__tbox_gpsinfo__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.TboxGPSInfo",
  "TboxGPSInfo",
  "Tbox__Net__TboxGPSInfo",
  "tbox.net",
  sizeof(Tbox__Net__TboxGPSInfo),
  1,
  tbox__net__tbox_gpsinfo__field_descriptors,
  tbox__net__tbox_gpsinfo__field_indices_by_name,
  1,  tbox__net__tbox_gpsinfo__number_ranges,
  (ProtobufCMessageInit) tbox__net__tbox_gpsinfo__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__tbox_wifi_client_info__field_descriptors[3] =
{
  {
    "hostname",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxWifiClientInfo, hostname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxWifiClientInfo, ip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxWifiClientInfo, mac),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__tbox_wifi_client_info__field_indices_by_name[] = {
  0,   /* field[0] = hostname */
  1,   /* field[1] = ip */
  2,   /* field[2] = mac */
};
static const ProtobufCIntRange tbox__net__tbox_wifi_client_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tbox__net__tbox_wifi_client_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.TboxWifiClientInfo",
  "TboxWifiClientInfo",
  "Tbox__Net__TboxWifiClientInfo",
  "tbox.net",
  sizeof(Tbox__Net__TboxWifiClientInfo),
  3,
  tbox__net__tbox_wifi_client_info__field_descriptors,
  tbox__net__tbox_wifi_client_info__field_indices_by_name,
  1,  tbox__net__tbox_wifi_client_info__number_ranges,
  (ProtobufCMessageInit) tbox__net__tbox_wifi_client_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__wifi_status__field_descriptors[7] =
{
  {
    "wifi_enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__WifiStatus, wifi_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_ap_ssid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__WifiStatus, wifi_ap_ssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_ap_password",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__WifiStatus, wifi_ap_password),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_ap_bandwidth",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__WifiStatus, wifi_ap_bandwidth),
    &tbox__net__wifi_bandwidth__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_ap_maxlinks",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__WifiStatus, wifi_ap_maxlinks),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_app_macaddress",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__WifiStatus, wifi_app_macaddress),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_client_list",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Tbox__Net__WifiStatus, n_wifi_client_list),
    offsetof(Tbox__Net__WifiStatus, wifi_client_list),
    &tbox__net__tbox_wifi_client_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__wifi_status__field_indices_by_name[] = {
  3,   /* field[3] = wifi_ap_bandwidth */
  4,   /* field[4] = wifi_ap_maxlinks */
  2,   /* field[2] = wifi_ap_password */
  1,   /* field[1] = wifi_ap_ssid */
  5,   /* field[5] = wifi_app_macaddress */
  6,   /* field[6] = wifi_client_list */
  0,   /* field[0] = wifi_enabled */
};
static const ProtobufCIntRange tbox__net__wifi_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor tbox__net__wifi_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.WifiStatus",
  "WifiStatus",
  "Tbox__Net__WifiStatus",
  "tbox.net",
  sizeof(Tbox__Net__WifiStatus),
  7,
  tbox__net__wifi_status__field_descriptors,
  tbox__net__wifi_status__field_indices_by_name,
  1,  tbox__net__wifi_status__number_ranges,
  (ProtobufCMessageInit) tbox__net__wifi_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__wifi_set_cmd__field_descriptors[2] =
{
  {
    "cmd",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__WifiSetCmd, cmd),
    &tbox__net__wifi_set_cmd_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_para_value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__WifiSetCmd, cmd_para_value),
    &tbox__net__wifi_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__wifi_set_cmd__field_indices_by_name[] = {
  0,   /* field[0] = cmd */
  1,   /* field[1] = cmd_para_value */
};
static const ProtobufCIntRange tbox__net__wifi_set_cmd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tbox__net__wifi_set_cmd__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.WifiSetCmd",
  "WifiSetCmd",
  "Tbox__Net__WifiSetCmd",
  "tbox.net",
  sizeof(Tbox__Net__WifiSetCmd),
  2,
  tbox__net__wifi_set_cmd__field_descriptors,
  tbox__net__wifi_set_cmd__field_indices_by_name,
  1,  tbox__net__wifi_set_cmd__number_ranges,
  (ProtobufCMessageInit) tbox__net__wifi_set_cmd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__wifi_set_result__field_descriptors[2] =
{
  {
    "cmd",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__WifiSetResult, cmd),
    &tbox__net__wifi_set_cmd_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stauts",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__WifiSetResult, stauts),
    &tbox__net__wifi_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__wifi_set_result__field_indices_by_name[] = {
  0,   /* field[0] = cmd */
  1,   /* field[1] = stauts */
};
static const ProtobufCIntRange tbox__net__wifi_set_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tbox__net__wifi_set_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.WifiSetResult",
  "WifiSetResult",
  "Tbox__Net__WifiSetResult",
  "tbox.net",
  sizeof(Tbox__Net__WifiSetResult),
  2,
  tbox__net__wifi_set_result__field_descriptors,
  tbox__net__wifi_set_result__field_indices_by_name,
  1,  tbox__net__wifi_set_result__number_ranges,
  (ProtobufCMessageInit) tbox__net__wifi_set_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__client_hello__field_descriptors[2] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__ClientHello, mode),
    &tbox__net__sym__enc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "random",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__ClientHello, random),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__client_hello__field_indices_by_name[] = {
  0,   /* field[0] = mode */
  1,   /* field[1] = random */
};
static const ProtobufCIntRange tbox__net__client_hello__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tbox__net__client_hello__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.ClientHello",
  "ClientHello",
  "Tbox__Net__ClientHello",
  "tbox.net",
  sizeof(Tbox__Net__ClientHello),
  2,
  tbox__net__client_hello__field_descriptors,
  tbox__net__client_hello__field_indices_by_name,
  1,  tbox__net__client_hello__number_ranges,
  (ProtobufCMessageInit) tbox__net__client_hello__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__client_send_certificate__field_descriptors[3] =
{
  {
    "random",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__ClientSendCertificate, random),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SHA256",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__ClientSendCertificate, sha256),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "N512",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__ClientSendCertificate, n512),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__client_send_certificate__field_indices_by_name[] = {
  2,   /* field[2] = N512 */
  1,   /* field[1] = SHA256 */
  0,   /* field[0] = random */
};
static const ProtobufCIntRange tbox__net__client_send_certificate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tbox__net__client_send_certificate__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.ClientSendCertificate",
  "ClientSendCertificate",
  "Tbox__Net__ClientSendCertificate",
  "tbox.net",
  sizeof(Tbox__Net__ClientSendCertificate),
  3,
  tbox__net__client_send_certificate__field_descriptors,
  tbox__net__client_send_certificate__field_indices_by_name,
  1,  tbox__net__client_send_certificate__number_ranges,
  (ProtobufCMessageInit) tbox__net__client_send_certificate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__client_finish__field_descriptors[1] =
{
  {
    "DECODED",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__ClientFinish, decoded),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__client_finish__field_indices_by_name[] = {
  0,   /* field[0] = DECODED */
};
static const ProtobufCIntRange tbox__net__client_finish__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tbox__net__client_finish__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.ClientFinish",
  "ClientFinish",
  "Tbox__Net__ClientFinish",
  "tbox.net",
  sizeof(Tbox__Net__ClientFinish),
  1,
  tbox__net__client_finish__field_descriptors,
  tbox__net__client_finish__field_indices_by_name,
  1,  tbox__net__client_finish__number_ranges,
  (ProtobufCMessageInit) tbox__net__client_finish__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__certification_step__field_descriptors[3] =
{
  {
    "start",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CertificationStep, start),
    &tbox__net__client_hello__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sent",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CertificationStep, sent),
    &tbox__net__client_send_certificate__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "finsh",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CertificationStep, finsh),
    &tbox__net__client_finish__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__certification_step__field_indices_by_name[] = {
  2,   /* field[2] = finsh */
  1,   /* field[1] = sent */
  0,   /* field[0] = start */
};
static const ProtobufCIntRange tbox__net__certification_step__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tbox__net__certification_step__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.CertificationStep",
  "CertificationStep",
  "Tbox__Net__CertificationStep",
  "tbox.net",
  sizeof(Tbox__Net__CertificationStep),
  3,
  tbox__net__certification_step__field_descriptors,
  tbox__net__certification_step__field_indices_by_name,
  1,  tbox__net__certification_step__number_ranges,
  (ProtobufCMessageInit) tbox__net__certification_step__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__certification_cmd__field_descriptors[2] =
{
  {
    "cmd",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CertificationCmd, cmd),
    &tbox__net__certification_cmd_eum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_para_value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CertificationCmd, cmd_para_value),
    &tbox__net__certification_step__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__certification_cmd__field_indices_by_name[] = {
  0,   /* field[0] = cmd */
  1,   /* field[1] = cmd_para_value */
};
static const ProtobufCIntRange tbox__net__certification_cmd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tbox__net__certification_cmd__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.CertificationCmd",
  "CertificationCmd",
  "Tbox__Net__CertificationCmd",
  "tbox.net",
  sizeof(Tbox__Net__CertificationCmd),
  2,
  tbox__net__certification_cmd__field_descriptors,
  tbox__net__certification_cmd__field_indices_by_name,
  1,  tbox__net__certification_cmd__number_ranges,
  (ProtobufCMessageInit) tbox__net__certification_cmd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__server_send_certificate__field_descriptors[2] =
{
  {
    "random",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__ServerSendCertificate, random),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tbox_certificate",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__ServerSendCertificate, tbox_certificate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__server_send_certificate__field_indices_by_name[] = {
  0,   /* field[0] = random */
  1,   /* field[1] = tbox_certificate */
};
static const ProtobufCIntRange tbox__net__server_send_certificate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tbox__net__server_send_certificate__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.ServerSendCertificate",
  "ServerSendCertificate",
  "Tbox__Net__ServerSendCertificate",
  "tbox.net",
  sizeof(Tbox__Net__ServerSendCertificate),
  2,
  tbox__net__server_send_certificate__field_descriptors,
  tbox__net__server_send_certificate__field_indices_by_name,
  1,  tbox__net__server_send_certificate__number_ranges,
  (ProtobufCMessageInit) tbox__net__server_send_certificate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__server_finish__field_descriptors[1] =
{
  {
    "DECODED",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__ServerFinish, decoded),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__server_finish__field_indices_by_name[] = {
  0,   /* field[0] = DECODED */
};
static const ProtobufCIntRange tbox__net__server_finish__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tbox__net__server_finish__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.ServerFinish",
  "ServerFinish",
  "Tbox__Net__ServerFinish",
  "tbox.net",
  sizeof(Tbox__Net__ServerFinish),
  1,
  tbox__net__server_finish__field_descriptors,
  tbox__net__server_finish__field_indices_by_name,
  1,  tbox__net__server_finish__number_ranges,
  (ProtobufCMessageInit) tbox__net__server_finish__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__certification_status__field_descriptors[2] =
{
  {
    "send",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CertificationStatus, send),
    &tbox__net__server_send_certificate__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "finish",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CertificationStatus, finish),
    &tbox__net__server_finish__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__certification_status__field_indices_by_name[] = {
  1,   /* field[1] = finish */
  0,   /* field[0] = send */
};
static const ProtobufCIntRange tbox__net__certification_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tbox__net__certification_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.CertificationStatus",
  "CertificationStatus",
  "Tbox__Net__CertificationStatus",
  "tbox.net",
  sizeof(Tbox__Net__CertificationStatus),
  2,
  tbox__net__certification_status__field_descriptors,
  tbox__net__certification_status__field_indices_by_name,
  1,  tbox__net__certification_status__number_ranges,
  (ProtobufCMessageInit) tbox__net__certification_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__certification_result__field_descriptors[2] =
{
  {
    "cmd",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CertificationResult, cmd),
    &tbox__net__certification_cmd_eum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__CertificationResult, status),
    &tbox__net__certification_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__certification_result__field_indices_by_name[] = {
  0,   /* field[0] = cmd */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange tbox__net__certification_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tbox__net__certification_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.CertificationResult",
  "CertificationResult",
  "Tbox__Net__CertificationResult",
  "tbox.net",
  sizeof(Tbox__Net__CertificationResult),
  2,
  tbox__net__certification_result__field_descriptors,
  tbox__net__certification_result__field_indices_by_name,
  1,  tbox__net__certification_result__number_ranges,
  (ProtobufCMessageInit) tbox__net__certification_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__msg_result__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__MsgResult, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__MsgResult, error_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__msg_result__field_indices_by_name[] = {
  1,   /* field[1] = error_code */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange tbox__net__msg_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tbox__net__msg_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.MsgResult",
  "MsgResult",
  "Tbox__Net__MsgResult",
  "tbox.net",
  sizeof(Tbox__Net__MsgResult),
  2,
  tbox__net__msg_result__field_descriptors,
  tbox__net__msg_result__field_indices_by_name,
  1,  tbox__net__msg_result__number_ranges,
  (ProtobufCMessageInit) tbox__net__msg_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__top_message__field_descriptors[15] =
{
  {
    "message_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, message_type),
    &tbox__net__messagetype__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signal_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, signal_type),
    &tbox__net__signal_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signal_power",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, signal_power),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call_action",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, call_action),
    &tbox__net__call_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call_status",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, call_status),
    &tbox__net__call_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call_result",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, call_result),
    &tbox__net__call_action_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tbox_info",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, tbox_info),
    &tbox__net__tbox_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_set_cmd",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, wifi_set_cmd),
    &tbox__net__wifi_set_cmd__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_status",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, wifi_status),
    &tbox__net__wifi_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_set_result",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, wifi_set_result),
    &tbox__net__wifi_set_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tbox_gps_ctrl",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, tbox_gps_ctrl),
    &tbox__net__tbox_gpscmd__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tbox_gpsinfo",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, tbox_gpsinfo),
    &tbox__net__tbox_gpsinfo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Certification_ctrl",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, certification_ctrl),
    &tbox__net__certification_cmd__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Certification_result",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, certification_result),
    &tbox__net__certification_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg_result",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, msg_result),
    &tbox__net__msg_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__top_message__field_indices_by_name[] = {
  12,   /* field[12] = Certification_ctrl */
  13,   /* field[13] = Certification_result */
  3,   /* field[3] = call_action */
  5,   /* field[5] = call_result */
  4,   /* field[4] = call_status */
  0,   /* field[0] = message_type */
  14,   /* field[14] = msg_result */
  2,   /* field[2] = signal_power */
  1,   /* field[1] = signal_type */
  10,   /* field[10] = tbox_gps_ctrl */
  11,   /* field[11] = tbox_gpsinfo */
  6,   /* field[6] = tbox_info */
  7,   /* field[7] = wifi_set_cmd */
  9,   /* field[9] = wifi_set_result */
  8,   /* field[8] = wifi_status */
};
static const ProtobufCIntRange tbox__net__top_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor tbox__net__top_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.TopMessage",
  "TopMessage",
  "Tbox__Net__TopMessage",
  "tbox.net",
  sizeof(Tbox__Net__TopMessage),
  15,
  tbox__net__top_message__field_descriptors,
  tbox__net__top_message__field_indices_by_name,
  1,  tbox__net__top_message__number_ranges,
  (ProtobufCMessageInit) tbox__net__top_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue tbox__net__messagetype__enum_values_by_number[23] =
{
  { "REQUEST_RESPONSE_NONE", "TBOX__NET__MESSAGETYPE__REQUEST_RESPONSE_NONE", 0 },
  { "REQUEST_HEARTBEAT_SIGNAL", "TBOX__NET__MESSAGETYPE__REQUEST_HEARTBEAT_SIGNAL", 1 },
  { "RESPONSE_HEARTBEAT_RESULT", "TBOX__NET__MESSAGETYPE__RESPONSE_HEARTBEAT_RESULT", 2 },
  { "REQUEST_NETWORK_SIGNAL_STRENGTH", "TBOX__NET__MESSAGETYPE__REQUEST_NETWORK_SIGNAL_STRENGTH", 3 },
  { "RESPONSE_NETWORK_SIGNAL_STRENGTH", "TBOX__NET__MESSAGETYPE__RESPONSE_NETWORK_SIGNAL_STRENGTH", 4 },
  { "REQUEST_CALL_ACTION", "TBOX__NET__MESSAGETYPE__REQUEST_CALL_ACTION", 5 },
  { "RESPONSE_CALL_ACTION_RESULT", "TBOX__NET__MESSAGETYPE__RESPONSE_CALL_ACTION_RESULT", 6 },
  { "RESPONSE_CALL_STATUS", "TBOX__NET__MESSAGETYPE__RESPONSE_CALL_STATUS", 7 },
  { "REQUEST_TBOX_INFO", "TBOX__NET__MESSAGETYPE__REQUEST_TBOX_INFO", 8 },
  { "RESPONSE_TBOX_INFO", "TBOX__NET__MESSAGETYPE__RESPONSE_TBOX_INFO", 9 },
  { "REQUEST_WIFI_GET_STATUS", "TBOX__NET__MESSAGETYPE__REQUEST_WIFI_GET_STATUS", 10 },
  { "RESPONSE_WIFI_STATUS", "TBOX__NET__MESSAGETYPE__RESPONSE_WIFI_STATUS", 11 },
  { "REQUEST_SETUP_WIFI", "TBOX__NET__MESSAGETYPE__REQUEST_SETUP_WIFI", 12 },
  { "RESPONSE_WIFI_SETUP_RESULT", "TBOX__NET__MESSAGETYPE__RESPONSE_WIFI_SETUP_RESULT", 13 },
  { "REQUEST_WIFI_MACADDRESS", "TBOX__NET__MESSAGETYPE__REQUEST_WIFI_MACADDRESS", 14 },
  { "RESPONSE_WIFI_MACADDRESS_RESULT", "TBOX__NET__MESSAGETYPE__RESPONSE_WIFI_MACADDRESS_RESULT", 15 },
  { "REQUEST_WIFI_CLIENT_LIST", "TBOX__NET__MESSAGETYPE__REQUEST_WIFI_CLIENT_LIST", 16 },
  { "RESPONSE_WIFI_CLIENT_LIST_RESULT", "TBOX__NET__MESSAGETYPE__RESPONSE_WIFI_CLIENT_LIST_RESULT", 17 },
  { "REQUEST_TBOX_GPS_SET", "TBOX__NET__MESSAGETYPE__REQUEST_TBOX_GPS_SET", 18 },
  { "RESPONSE_TBOX_GPS_SET_RESULT", "TBOX__NET__MESSAGETYPE__RESPONSE_TBOX_GPS_SET_RESULT", 19 },
  { "RESPONSE_TBOX_GPSINFO_RESULT", "TBOX__NET__MESSAGETYPE__RESPONSE_TBOX_GPSINFO_RESULT", 20 },
  { "REQUEST_CERTIFICATION", "TBOX__NET__MESSAGETYPE__REQUEST_CERTIFICATION", 21 },
  { "RESPONSE_CERTIFICATION_RESULT", "TBOX__NET__MESSAGETYPE__RESPONSE_CERTIFICATION_RESULT", 22 },
};
static const ProtobufCIntRange tbox__net__messagetype__value_ranges[] = {
{0, 0},{0, 23}
};
static const ProtobufCEnumValueIndex tbox__net__messagetype__enum_values_by_name[23] =
{
  { "REQUEST_CALL_ACTION", 5 },
  { "REQUEST_CERTIFICATION", 21 },
  { "REQUEST_HEARTBEAT_SIGNAL", 1 },
  { "REQUEST_NETWORK_SIGNAL_STRENGTH", 3 },
  { "REQUEST_RESPONSE_NONE", 0 },
  { "REQUEST_SETUP_WIFI", 12 },
  { "REQUEST_TBOX_GPS_SET", 18 },
  { "REQUEST_TBOX_INFO", 8 },
  { "REQUEST_WIFI_CLIENT_LIST", 16 },
  { "REQUEST_WIFI_GET_STATUS", 10 },
  { "REQUEST_WIFI_MACADDRESS", 14 },
  { "RESPONSE_CALL_ACTION_RESULT", 6 },
  { "RESPONSE_CALL_STATUS", 7 },
  { "RESPONSE_CERTIFICATION_RESULT", 22 },
  { "RESPONSE_HEARTBEAT_RESULT", 2 },
  { "RESPONSE_NETWORK_SIGNAL_STRENGTH", 4 },
  { "RESPONSE_TBOX_GPSINFO_RESULT", 20 },
  { "RESPONSE_TBOX_GPS_SET_RESULT", 19 },
  { "RESPONSE_TBOX_INFO", 9 },
  { "RESPONSE_WIFI_CLIENT_LIST_RESULT", 17 },
  { "RESPONSE_WIFI_MACADDRESS_RESULT", 15 },
  { "RESPONSE_WIFI_SETUP_RESULT", 13 },
  { "RESPONSE_WIFI_STATUS", 11 },
};
const ProtobufCEnumDescriptor tbox__net__messagetype__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.Messagetype",
  "Messagetype",
  "Tbox__Net__Messagetype",
  "tbox.net",
  23,
  tbox__net__messagetype__enum_values_by_number,
  23,
  tbox__net__messagetype__enum_values_by_name,
  1,
  tbox__net__messagetype__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__signal_type__enum_values_by_number[4] =
{
  { "NONE_SIGNAL", "TBOX__NET__SIGNAL_TYPE__NONE_SIGNAL", 0 },
  { "GSM", "TBOX__NET__SIGNAL_TYPE__GSM", 1 },
  { "UMTS", "TBOX__NET__SIGNAL_TYPE__UMTS", 2 },
  { "LTE", "TBOX__NET__SIGNAL_TYPE__LTE", 3 },
};
static const ProtobufCIntRange tbox__net__signal_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex tbox__net__signal_type__enum_values_by_name[4] =
{
  { "GSM", 1 },
  { "LTE", 3 },
  { "NONE_SIGNAL", 0 },
  { "UMTS", 2 },
};
const ProtobufCEnumDescriptor tbox__net__signal_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.SignalType",
  "SignalType",
  "Tbox__Net__SignalType",
  "tbox.net",
  4,
  tbox__net__signal_type__enum_values_by_number,
  4,
  tbox__net__signal_type__enum_values_by_name,
  1,
  tbox__net__signal_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__call_type__enum_values_by_number[3] =
{
  { "ECALL", "TBOX__NET__CALL_TYPE__ECALL", 0 },
  { "BCALL", "TBOX__NET__CALL_TYPE__BCALL", 1 },
  { "ICALL", "TBOX__NET__CALL_TYPE__ICALL", 2 },
};
static const ProtobufCIntRange tbox__net__call_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex tbox__net__call_type__enum_values_by_name[3] =
{
  { "BCALL", 1 },
  { "ECALL", 0 },
  { "ICALL", 2 },
};
const ProtobufCEnumDescriptor tbox__net__call_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.CallType",
  "CallType",
  "Tbox__Net__CallType",
  "tbox.net",
  3,
  tbox__net__call_type__enum_values_by_number,
  3,
  tbox__net__call_type__enum_values_by_name,
  1,
  tbox__net__call_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__call_action_enum__enum_values_by_number[2] =
{
  { "START_CALL", "TBOX__NET__CALL_ACTION_ENUM__START_CALL", 0 },
  { "END_CALL", "TBOX__NET__CALL_ACTION_ENUM__END_CALL", 1 },
};
static const ProtobufCIntRange tbox__net__call_action_enum__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex tbox__net__call_action_enum__enum_values_by_name[2] =
{
  { "END_CALL", 1 },
  { "START_CALL", 0 },
};
const ProtobufCEnumDescriptor tbox__net__call_action_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.CallActionEnum",
  "CallActionEnum",
  "Tbox__Net__CallActionEnum",
  "tbox.net",
  2,
  tbox__net__call_action_enum__enum_values_by_number,
  2,
  tbox__net__call_action_enum__enum_values_by_name,
  1,
  tbox__net__call_action_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__call_action_result_enum__enum_values_by_number[6] =
{
  { "CALL_ACTION_SUCCESS", "TBOX__NET__CALL_ACTION_RESULT_ENUM__CALL_ACTION_SUCCESS", 0 },
  { "CALL_ACTION_NONSUPPORT", "TBOX__NET__CALL_ACTION_RESULT_ENUM__CALL_ACTION_NONSUPPORT", 1 },
  { "START_FAILED_CALL_PROCESSING", "TBOX__NET__CALL_ACTION_RESULT_ENUM__START_FAILED_CALL_PROCESSING", 2 },
  { "START_FAILED_OTHER_ERROR", "TBOX__NET__CALL_ACTION_RESULT_ENUM__START_FAILED_OTHER_ERROR", 3 },
  { "END_FAILED_NO_CURRENT_CALL", "TBOX__NET__CALL_ACTION_RESULT_ENUM__END_FAILED_NO_CURRENT_CALL", 4 },
  { "END_FAILED_OTHER_ERROR", "TBOX__NET__CALL_ACTION_RESULT_ENUM__END_FAILED_OTHER_ERROR", 5 },
};
static const ProtobufCIntRange tbox__net__call_action_result_enum__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex tbox__net__call_action_result_enum__enum_values_by_name[6] =
{
  { "CALL_ACTION_NONSUPPORT", 1 },
  { "CALL_ACTION_SUCCESS", 0 },
  { "END_FAILED_NO_CURRENT_CALL", 4 },
  { "END_FAILED_OTHER_ERROR", 5 },
  { "START_FAILED_CALL_PROCESSING", 2 },
  { "START_FAILED_OTHER_ERROR", 3 },
};
const ProtobufCEnumDescriptor tbox__net__call_action_result_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.CallActionResultEnum",
  "CallActionResultEnum",
  "Tbox__Net__CallActionResultEnum",
  "tbox.net",
  6,
  tbox__net__call_action_result_enum__enum_values_by_number,
  6,
  tbox__net__call_action_result_enum__enum_values_by_name,
  1,
  tbox__net__call_action_result_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__call_status_enum__enum_values_by_number[5] =
{
  { "CALL_IN", "TBOX__NET__CALL_STATUS_ENUM__CALL_IN", 0 },
  { "CALL_OUT", "TBOX__NET__CALL_STATUS_ENUM__CALL_OUT", 1 },
  { "CALL_RING", "TBOX__NET__CALL_STATUS_ENUM__CALL_RING", 2 },
  { "CALL_CONNECTED", "TBOX__NET__CALL_STATUS_ENUM__CALL_CONNECTED", 3 },
  { "CALL_DISCONNECTED", "TBOX__NET__CALL_STATUS_ENUM__CALL_DISCONNECTED", 4 },
};
static const ProtobufCIntRange tbox__net__call_status_enum__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex tbox__net__call_status_enum__enum_values_by_name[5] =
{
  { "CALL_CONNECTED", 3 },
  { "CALL_DISCONNECTED", 4 },
  { "CALL_IN", 0 },
  { "CALL_OUT", 1 },
  { "CALL_RING", 2 },
};
const ProtobufCEnumDescriptor tbox__net__call_status_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.CallStatusEnum",
  "CallStatusEnum",
  "Tbox__Net__CallStatusEnum",
  "tbox.net",
  5,
  tbox__net__call_status_enum__enum_values_by_number,
  5,
  tbox__net__call_status_enum__enum_values_by_name,
  1,
  tbox__net__call_status_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__hemisphere__enum_values_by_number[4] =
{
  { "NORTH_LATI", "TBOX__NET__HEMISPHERE__NORTH_LATI", 0 },
  { "SOUTH_LATI", "TBOX__NET__HEMISPHERE__SOUTH_LATI", 1 },
  { "EAST_LONGI", "TBOX__NET__HEMISPHERE__EAST_LONGI", 2 },
  { "WEST_LONGI", "TBOX__NET__HEMISPHERE__WEST_LONGI", 3 },
};
static const ProtobufCIntRange tbox__net__hemisphere__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex tbox__net__hemisphere__enum_values_by_name[4] =
{
  { "EAST_LONGI", 2 },
  { "NORTH_LATI", 0 },
  { "SOUTH_LATI", 1 },
  { "WEST_LONGI", 3 },
};
const ProtobufCEnumDescriptor tbox__net__hemisphere__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.Hemisphere",
  "Hemisphere",
  "Tbox__Net__Hemisphere",
  "tbox.net",
  4,
  tbox__net__hemisphere__enum_values_by_number,
  4,
  tbox__net__hemisphere__enum_values_by_name,
  1,
  tbox__net__hemisphere__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__gps__send__on_off__enum_values_by_number[3] =
{
  { "GPS_ON", "TBOX__NET__GPS__SEND__ON_OFF__GPS_ON", 0 },
  { "GPS_OFF", "TBOX__NET__GPS__SEND__ON_OFF__GPS_OFF", 1 },
  { "GPS_ONCE", "TBOX__NET__GPS__SEND__ON_OFF__GPS_ONCE", 2 },
};
static const ProtobufCIntRange tbox__net__gps__send__on_off__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex tbox__net__gps__send__on_off__enum_values_by_name[3] =
{
  { "GPS_OFF", 1 },
  { "GPS_ON", 0 },
  { "GPS_ONCE", 2 },
};
const ProtobufCEnumDescriptor tbox__net__gps__send__on_off__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.GPS_SEND_OnOff",
  "GPS_SEND_OnOff",
  "Tbox__Net__GPSSENDOnOff",
  "tbox.net",
  3,
  tbox__net__gps__send__on_off__enum_values_by_number,
  3,
  tbox__net__gps__send__on_off__enum_values_by_name,
  1,
  tbox__net__gps__send__on_off__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__wifi_bandwidth__enum_values_by_number[2] =
{
  { "BANDWIDTH_2G", "TBOX__NET__WIFI_BANDWIDTH__BANDWIDTH_2G", 0 },
  { "BANDWIDTH_5G", "TBOX__NET__WIFI_BANDWIDTH__BANDWIDTH_5G", 1 },
};
static const ProtobufCIntRange tbox__net__wifi_bandwidth__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex tbox__net__wifi_bandwidth__enum_values_by_name[2] =
{
  { "BANDWIDTH_2G", 0 },
  { "BANDWIDTH_5G", 1 },
};
const ProtobufCEnumDescriptor tbox__net__wifi_bandwidth__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.WifiBandwidth",
  "WifiBandwidth",
  "Tbox__Net__WifiBandwidth",
  "tbox.net",
  2,
  tbox__net__wifi_bandwidth__enum_values_by_number,
  2,
  tbox__net__wifi_bandwidth__enum_values_by_name,
  1,
  tbox__net__wifi_bandwidth__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__wifi_set_cmd_enum__enum_values_by_number[5] =
{
  { "WIFI_ENABLE", "TBOX__NET__WIFI_SET_CMD_ENUM__WIFI_ENABLE", 0 },
  { "WIFI_AP_SSID", "TBOX__NET__WIFI_SET_CMD_ENUM__WIFI_AP_SSID", 1 },
  { "WIFI_AP_PASSWORD", "TBOX__NET__WIFI_SET_CMD_ENUM__WIFI_AP_PASSWORD", 2 },
  { "WIFI_AP_BANDWIDTH", "TBOX__NET__WIFI_SET_CMD_ENUM__WIFI_AP_BANDWIDTH", 3 },
  { "WIFI_AP_MAXLINKS", "TBOX__NET__WIFI_SET_CMD_ENUM__WIFI_AP_MAXLINKS", 4 },
};
static const ProtobufCIntRange tbox__net__wifi_set_cmd_enum__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex tbox__net__wifi_set_cmd_enum__enum_values_by_name[5] =
{
  { "WIFI_AP_BANDWIDTH", 3 },
  { "WIFI_AP_MAXLINKS", 4 },
  { "WIFI_AP_PASSWORD", 2 },
  { "WIFI_AP_SSID", 1 },
  { "WIFI_ENABLE", 0 },
};
const ProtobufCEnumDescriptor tbox__net__wifi_set_cmd_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.WifiSetCmdEnum",
  "WifiSetCmdEnum",
  "Tbox__Net__WifiSetCmdEnum",
  "tbox.net",
  5,
  tbox__net__wifi_set_cmd_enum__enum_values_by_number,
  5,
  tbox__net__wifi_set_cmd_enum__enum_values_by_name,
  1,
  tbox__net__wifi_set_cmd_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__certification_cmd_eum__enum_values_by_number[5] =
{
  { "CLIENTHELLO", "TBOX__NET__CERTIFICATION_CMD_EUM__CLIENTHELLO", 0 },
  { "SERVICESENDCERTIFICATION", "TBOX__NET__CERTIFICATION_CMD_EUM__SERVICESENDCERTIFICATION", 1 },
  { "CLIENTSENDCERTIFICATION", "TBOX__NET__CERTIFICATION_CMD_EUM__CLIENTSENDCERTIFICATION", 2 },
  { "SERVICEFINISHED", "TBOX__NET__CERTIFICATION_CMD_EUM__SERVICEFINISHED", 3 },
  { "CLIENTFINISHED", "TBOX__NET__CERTIFICATION_CMD_EUM__CLIENTFINISHED", 4 },
};
static const ProtobufCIntRange tbox__net__certification_cmd_eum__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex tbox__net__certification_cmd_eum__enum_values_by_name[5] =
{
  { "CLIENTFINISHED", 4 },
  { "CLIENTHELLO", 0 },
  { "CLIENTSENDCERTIFICATION", 2 },
  { "SERVICEFINISHED", 3 },
  { "SERVICESENDCERTIFICATION", 1 },
};
const ProtobufCEnumDescriptor tbox__net__certification_cmd_eum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.CertificationCmdEum",
  "CertificationCmdEum",
  "Tbox__Net__CertificationCmdEum",
  "tbox.net",
  5,
  tbox__net__certification_cmd_eum__enum_values_by_number,
  5,
  tbox__net__certification_cmd_eum__enum_values_by_name,
  1,
  tbox__net__certification_cmd_eum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__sym__enc__enum_values_by_number[4] =
{
  { "SYM_ENC_NONE", "TBOX__NET__SYM__ENC__SYM_ENC_NONE", 0 },
  { "SYM_ENC_AES256_CBC", "TBOX__NET__SYM__ENC__SYM_ENC_AES256_CBC", 1 },
  { "SYM_ENC_3DES", "TBOX__NET__SYM__ENC__SYM_ENC_3DES", 2 },
  { "SYM_ENC_IDEA", "TBOX__NET__SYM__ENC__SYM_ENC_IDEA", 3 },
};
static const ProtobufCIntRange tbox__net__sym__enc__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex tbox__net__sym__enc__enum_values_by_name[4] =
{
  { "SYM_ENC_3DES", 2 },
  { "SYM_ENC_AES256_CBC", 1 },
  { "SYM_ENC_IDEA", 3 },
  { "SYM_ENC_NONE", 0 },
};
const ProtobufCEnumDescriptor tbox__net__sym__enc__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.Sym_Enc",
  "Sym_Enc",
  "Tbox__Net__SymEnc",
  "tbox.net",
  4,
  tbox__net__sym__enc__enum_values_by_number,
  4,
  tbox__net__sym__enc__enum_values_by_name,
  1,
  tbox__net__sym__enc__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
