/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: IVI_Tbox_v3.3.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "tbox_ivi_pb.h"
void   tbox__net__tbox_network_ctrl__init
                     (Tbox__Net__TboxNetworkCtrl         *message)
{
  static Tbox__Net__TboxNetworkCtrl init_value = TBOX__NET__TBOX_NETWORK_CTRL__INIT;
  *message = init_value;
}
size_t tbox__net__tbox_network_ctrl__get_packed_size
                     (const Tbox__Net__TboxNetworkCtrl *message)
{
  assert(message->base.descriptor == &tbox__net__tbox_network_ctrl__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__tbox_network_ctrl__pack
                     (const Tbox__Net__TboxNetworkCtrl *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__tbox_network_ctrl__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__tbox_network_ctrl__pack_to_buffer
                     (const Tbox__Net__TboxNetworkCtrl *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__tbox_network_ctrl__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__TboxNetworkCtrl *
       tbox__net__tbox_network_ctrl__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__TboxNetworkCtrl *)
     protobuf_c_message_unpack (&tbox__net__tbox_network_ctrl__descriptor,
                                allocator, len, data);
}
void   tbox__net__tbox_network_ctrl__free_unpacked
                     (Tbox__Net__TboxNetworkCtrl *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tbox__net__tbox_network_ctrl__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__call_action__init
                     (Tbox__Net__CallAction         *message)
{
  static Tbox__Net__CallAction init_value = TBOX__NET__CALL_ACTION__INIT;
  *message = init_value;
}
size_t tbox__net__call_action__get_packed_size
                     (const Tbox__Net__CallAction *message)
{
  assert(message->base.descriptor == &tbox__net__call_action__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__call_action__pack
                     (const Tbox__Net__CallAction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__call_action__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__call_action__pack_to_buffer
                     (const Tbox__Net__CallAction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__call_action__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__CallAction *
       tbox__net__call_action__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__CallAction *)
     protobuf_c_message_unpack (&tbox__net__call_action__descriptor,
                                allocator, len, data);
}
void   tbox__net__call_action__free_unpacked
                     (Tbox__Net__CallAction *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tbox__net__call_action__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__call_action_result__init
                     (Tbox__Net__CallActionResult         *message)
{
  static Tbox__Net__CallActionResult init_value = TBOX__NET__CALL_ACTION_RESULT__INIT;
  *message = init_value;
}
size_t tbox__net__call_action_result__get_packed_size
                     (const Tbox__Net__CallActionResult *message)
{
  assert(message->base.descriptor == &tbox__net__call_action_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__call_action_result__pack
                     (const Tbox__Net__CallActionResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__call_action_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__call_action_result__pack_to_buffer
                     (const Tbox__Net__CallActionResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__call_action_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__CallActionResult *
       tbox__net__call_action_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__CallActionResult *)
     protobuf_c_message_unpack (&tbox__net__call_action_result__descriptor,
                                allocator, len, data);
}
void   tbox__net__call_action_result__free_unpacked
                     (Tbox__Net__CallActionResult *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tbox__net__call_action_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__call_status__init
                     (Tbox__Net__CallStatus         *message)
{
  static Tbox__Net__CallStatus init_value = TBOX__NET__CALL_STATUS__INIT;
  *message = init_value;
}
size_t tbox__net__call_status__get_packed_size
                     (const Tbox__Net__CallStatus *message)
{
  assert(message->base.descriptor == &tbox__net__call_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__call_status__pack
                     (const Tbox__Net__CallStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__call_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__call_status__pack_to_buffer
                     (const Tbox__Net__CallStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__call_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__CallStatus *
       tbox__net__call_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__CallStatus *)
     protobuf_c_message_unpack (&tbox__net__call_status__descriptor,
                                allocator, len, data);
}
void   tbox__net__call_status__free_unpacked
                     (Tbox__Net__CallStatus *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tbox__net__call_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__tbox_info__init
                     (Tbox__Net__TboxInfo         *message)
{
  static Tbox__Net__TboxInfo init_value = TBOX__NET__TBOX_INFO__INIT;
  *message = init_value;
}
size_t tbox__net__tbox_info__get_packed_size
                     (const Tbox__Net__TboxInfo *message)
{
  assert(message->base.descriptor == &tbox__net__tbox_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__tbox_info__pack
                     (const Tbox__Net__TboxInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__tbox_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__tbox_info__pack_to_buffer
                     (const Tbox__Net__TboxInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__tbox_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__TboxInfo *
       tbox__net__tbox_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__TboxInfo *)
     protobuf_c_message_unpack (&tbox__net__tbox_info__descriptor,
                                allocator, len, data);
}
void   tbox__net__tbox_info__free_unpacked
                     (Tbox__Net__TboxInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tbox__net__tbox_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__tbox_gpscmd__init
                     (Tbox__Net__TboxGPSCmd         *message)
{
  static Tbox__Net__TboxGPSCmd init_value = TBOX__NET__TBOX_GPSCMD__INIT;
  *message = init_value;
}
size_t tbox__net__tbox_gpscmd__get_packed_size
                     (const Tbox__Net__TboxGPSCmd *message)
{
  assert(message->base.descriptor == &tbox__net__tbox_gpscmd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__tbox_gpscmd__pack
                     (const Tbox__Net__TboxGPSCmd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__tbox_gpscmd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__tbox_gpscmd__pack_to_buffer
                     (const Tbox__Net__TboxGPSCmd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__tbox_gpscmd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__TboxGPSCmd *
       tbox__net__tbox_gpscmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__TboxGPSCmd *)
     protobuf_c_message_unpack (&tbox__net__tbox_gpscmd__descriptor,
                                allocator, len, data);
}
void   tbox__net__tbox_gpscmd__free_unpacked
                     (Tbox__Net__TboxGPSCmd *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tbox__net__tbox_gpscmd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__tbox_gpsinfo__init
                     (Tbox__Net__TboxGPSInfo         *message)
{
  static Tbox__Net__TboxGPSInfo init_value = TBOX__NET__TBOX_GPSINFO__INIT;
  *message = init_value;
}
size_t tbox__net__tbox_gpsinfo__get_packed_size
                     (const Tbox__Net__TboxGPSInfo *message)
{
  assert(message->base.descriptor == &tbox__net__tbox_gpsinfo__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__tbox_gpsinfo__pack
                     (const Tbox__Net__TboxGPSInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__tbox_gpsinfo__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__tbox_gpsinfo__pack_to_buffer
                     (const Tbox__Net__TboxGPSInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__tbox_gpsinfo__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__TboxGPSInfo *
       tbox__net__tbox_gpsinfo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__TboxGPSInfo *)
     protobuf_c_message_unpack (&tbox__net__tbox_gpsinfo__descriptor,
                                allocator, len, data);
}
void   tbox__net__tbox_gpsinfo__free_unpacked
                     (Tbox__Net__TboxGPSInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tbox__net__tbox_gpsinfo__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__tbox_active_state__init
                     (Tbox__Net__TboxActiveState         *message)
{
  static Tbox__Net__TboxActiveState init_value = TBOX__NET__TBOX_ACTIVE_STATE__INIT;
  *message = init_value;
}
size_t tbox__net__tbox_active_state__get_packed_size
                     (const Tbox__Net__TboxActiveState *message)
{
  assert(message->base.descriptor == &tbox__net__tbox_active_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__tbox_active_state__pack
                     (const Tbox__Net__TboxActiveState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__tbox_active_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__tbox_active_state__pack_to_buffer
                     (const Tbox__Net__TboxActiveState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__tbox_active_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__TboxActiveState *
       tbox__net__tbox_active_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__TboxActiveState *)
     protobuf_c_message_unpack (&tbox__net__tbox_active_state__descriptor,
                                allocator, len, data);
}
void   tbox__net__tbox_active_state__free_unpacked
                     (Tbox__Net__TboxActiveState *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tbox__net__tbox_active_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__tbox_remote_diagnose__init
                     (Tbox__Net__TboxRemoteDiagnose         *message)
{
  static Tbox__Net__TboxRemoteDiagnose init_value = TBOX__NET__TBOX_REMOTE_DIAGNOSE__INIT;
  *message = init_value;
}
size_t tbox__net__tbox_remote_diagnose__get_packed_size
                     (const Tbox__Net__TboxRemoteDiagnose *message)
{
  assert(message->base.descriptor == &tbox__net__tbox_remote_diagnose__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__tbox_remote_diagnose__pack
                     (const Tbox__Net__TboxRemoteDiagnose *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__tbox_remote_diagnose__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__tbox_remote_diagnose__pack_to_buffer
                     (const Tbox__Net__TboxRemoteDiagnose *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__tbox_remote_diagnose__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__TboxRemoteDiagnose *
       tbox__net__tbox_remote_diagnose__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__TboxRemoteDiagnose *)
     protobuf_c_message_unpack (&tbox__net__tbox_remote_diagnose__descriptor,
                                allocator, len, data);
}
void   tbox__net__tbox_remote_diagnose__free_unpacked
                     (Tbox__Net__TboxRemoteDiagnose *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tbox__net__tbox_remote_diagnose__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__msg_result__init
                     (Tbox__Net__MsgResult         *message)
{
  static Tbox__Net__MsgResult init_value = TBOX__NET__MSG_RESULT__INIT;
  *message = init_value;
}
size_t tbox__net__msg_result__get_packed_size
                     (const Tbox__Net__MsgResult *message)
{
  assert(message->base.descriptor == &tbox__net__msg_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__msg_result__pack
                     (const Tbox__Net__MsgResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__msg_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__msg_result__pack_to_buffer
                     (const Tbox__Net__MsgResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__msg_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__MsgResult *
       tbox__net__msg_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__MsgResult *)
     protobuf_c_message_unpack (&tbox__net__msg_result__descriptor,
                                allocator, len, data);
}
void   tbox__net__msg_result__free_unpacked
                     (Tbox__Net__MsgResult *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tbox__net__msg_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tbox__net__top_message__init
                     (Tbox__Net__TopMessage         *message)
{
  static Tbox__Net__TopMessage init_value = TBOX__NET__TOP_MESSAGE__INIT;
  *message = init_value;
}
size_t tbox__net__top_message__get_packed_size
                     (const Tbox__Net__TopMessage *message)
{
  assert(message->base.descriptor == &tbox__net__top_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tbox__net__top_message__pack
                     (const Tbox__Net__TopMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tbox__net__top_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tbox__net__top_message__pack_to_buffer
                     (const Tbox__Net__TopMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tbox__net__top_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tbox__Net__TopMessage *
       tbox__net__top_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tbox__Net__TopMessage *)
     protobuf_c_message_unpack (&tbox__net__top_message__descriptor,
                                allocator, len, data);
}
void   tbox__net__top_message__free_unpacked
                     (Tbox__Net__TopMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tbox__net__top_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor tbox__net__tbox_network_ctrl__field_descriptors[2] =
{
  {
    "onoff",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Tbox__Net__TboxNetworkCtrl, has_onoff),
    offsetof(Tbox__Net__TboxNetworkCtrl, onoff),
    &tbox__net__network__send__on_off__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_cycle",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Tbox__Net__TboxNetworkCtrl, has_time_cycle),
    offsetof(Tbox__Net__TboxNetworkCtrl, time_cycle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__tbox_network_ctrl__field_indices_by_name[] = {
  0,   /* field[0] = onoff */
  1,   /* field[1] = time_cycle */
};
static const ProtobufCIntRange tbox__net__tbox_network_ctrl__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tbox__net__tbox_network_ctrl__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.TboxNetworkCtrl",
  "TboxNetworkCtrl",
  "Tbox__Net__TboxNetworkCtrl",
  "tbox.net",
  sizeof(Tbox__Net__TboxNetworkCtrl),
  2,
  tbox__net__tbox_network_ctrl__field_descriptors,
  tbox__net__tbox_network_ctrl__field_indices_by_name,
  1,  tbox__net__tbox_network_ctrl__number_ranges,
  (ProtobufCMessageInit) tbox__net__tbox_network_ctrl__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__call_action__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Tbox__Net__CallAction, has_type),
    offsetof(Tbox__Net__CallAction, type),
    &tbox__net__call_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Tbox__Net__CallAction, has_action),
    offsetof(Tbox__Net__CallAction, action),
    &tbox__net__call_action_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__call_action__field_indices_by_name[] = {
  1,   /* field[1] = action */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange tbox__net__call_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tbox__net__call_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.CallAction",
  "CallAction",
  "Tbox__Net__CallAction",
  "tbox.net",
  sizeof(Tbox__Net__CallAction),
  2,
  tbox__net__call_action__field_descriptors,
  tbox__net__call_action__field_indices_by_name,
  1,  tbox__net__call_action__number_ranges,
  (ProtobufCMessageInit) tbox__net__call_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__call_action_result__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Tbox__Net__CallActionResult, has_type),
    offsetof(Tbox__Net__CallActionResult, type),
    &tbox__net__call_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Tbox__Net__CallActionResult, has_action),
    offsetof(Tbox__Net__CallActionResult, action),
    &tbox__net__call_action_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Tbox__Net__CallActionResult, has_result),
    offsetof(Tbox__Net__CallActionResult, result),
    &tbox__net__call_action_result_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__call_action_result__field_indices_by_name[] = {
  1,   /* field[1] = action */
  2,   /* field[2] = result */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange tbox__net__call_action_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tbox__net__call_action_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.CallActionResult",
  "CallActionResult",
  "Tbox__Net__CallActionResult",
  "tbox.net",
  sizeof(Tbox__Net__CallActionResult),
  3,
  tbox__net__call_action_result__field_descriptors,
  tbox__net__call_action_result__field_indices_by_name,
  1,  tbox__net__call_action_result__number_ranges,
  (ProtobufCMessageInit) tbox__net__call_action_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__call_status__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Tbox__Net__CallStatus, has_type),
    offsetof(Tbox__Net__CallStatus, type),
    &tbox__net__call_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call_status",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Tbox__Net__CallStatus, has_call_status),
    offsetof(Tbox__Net__CallStatus, call_status),
    &tbox__net__call_status_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reserve",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Tbox__Net__CallStatus, has_reserve),
    offsetof(Tbox__Net__CallStatus, reserve),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__call_status__field_indices_by_name[] = {
  1,   /* field[1] = call_status */
  2,   /* field[2] = reserve */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange tbox__net__call_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tbox__net__call_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.CallStatus",
  "CallStatus",
  "Tbox__Net__CallStatus",
  "tbox.net",
  sizeof(Tbox__Net__CallStatus),
  3,
  tbox__net__call_status__field_descriptors,
  tbox__net__call_status__field_indices_by_name,
  1,  tbox__net__call_status__number_ranges,
  (ProtobufCMessageInit) tbox__net__call_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__tbox_info__field_descriptors[6] =
{
  {
    "software_version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxInfo, software_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hardware_version",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxInfo, hardware_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iccid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxInfo, iccid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pdid",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxInfo, pdid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imei",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxInfo, imei),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vin",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxInfo, vin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__tbox_info__field_indices_by_name[] = {
  1,   /* field[1] = hardware_version */
  2,   /* field[2] = iccid */
  4,   /* field[4] = imei */
  3,   /* field[3] = pdid */
  0,   /* field[0] = software_version */
  5,   /* field[5] = vin */
};
static const ProtobufCIntRange tbox__net__tbox_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor tbox__net__tbox_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.TboxInfo",
  "TboxInfo",
  "Tbox__Net__TboxInfo",
  "tbox.net",
  sizeof(Tbox__Net__TboxInfo),
  6,
  tbox__net__tbox_info__field_descriptors,
  tbox__net__tbox_info__field_indices_by_name,
  1,  tbox__net__tbox_info__number_ranges,
  (ProtobufCMessageInit) tbox__net__tbox_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__tbox_gpscmd__field_descriptors[2] =
{
  {
    "onoff",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Tbox__Net__TboxGPSCmd, has_onoff),
    offsetof(Tbox__Net__TboxGPSCmd, onoff),
    &tbox__net__gps__send__on_off__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_cycle",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Tbox__Net__TboxGPSCmd, has_time_cycle),
    offsetof(Tbox__Net__TboxGPSCmd, time_cycle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__tbox_gpscmd__field_indices_by_name[] = {
  0,   /* field[0] = onoff */
  1,   /* field[1] = time_cycle */
};
static const ProtobufCIntRange tbox__net__tbox_gpscmd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tbox__net__tbox_gpscmd__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.TboxGPSCmd",
  "TboxGPSCmd",
  "Tbox__Net__TboxGPSCmd",
  "tbox.net",
  sizeof(Tbox__Net__TboxGPSCmd),
  2,
  tbox__net__tbox_gpscmd__field_descriptors,
  tbox__net__tbox_gpscmd__field_indices_by_name,
  1,  tbox__net__tbox_gpscmd__number_ranges,
  (ProtobufCMessageInit) tbox__net__tbox_gpscmd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__tbox_gpsinfo__field_descriptors[1] =
{
  {
    "nmea",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxGPSInfo, nmea),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__tbox_gpsinfo__field_indices_by_name[] = {
  0,   /* field[0] = nmea */
};
static const ProtobufCIntRange tbox__net__tbox_gpsinfo__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tbox__net__tbox_gpsinfo__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.TboxGPSInfo",
  "TboxGPSInfo",
  "Tbox__Net__TboxGPSInfo",
  "tbox.net",
  sizeof(Tbox__Net__TboxGPSInfo),
  1,
  tbox__net__tbox_gpsinfo__field_descriptors,
  tbox__net__tbox_gpsinfo__field_indices_by_name,
  1,  tbox__net__tbox_gpsinfo__number_ranges,
  (ProtobufCMessageInit) tbox__net__tbox_gpsinfo__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__tbox_active_state__field_descriptors[1] =
{
  {
    "active_state",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Tbox__Net__TboxActiveState, has_active_state),
    offsetof(Tbox__Net__TboxActiveState, active_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__tbox_active_state__field_indices_by_name[] = {
  0,   /* field[0] = active_state */
};
static const ProtobufCIntRange tbox__net__tbox_active_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tbox__net__tbox_active_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.TboxActiveState",
  "TboxActiveState",
  "Tbox__Net__TboxActiveState",
  "tbox.net",
  sizeof(Tbox__Net__TboxActiveState),
  1,
  tbox__net__tbox_active_state__field_descriptors,
  tbox__net__tbox_active_state__field_indices_by_name,
  1,  tbox__net__tbox_active_state__number_ranges,
  (ProtobufCMessageInit) tbox__net__tbox_active_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__tbox_remote_diagnose__field_descriptors[9] =
{
  {
    "vin",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TboxRemoteDiagnose, vin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eventid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Tbox__Net__TboxRemoteDiagnose, has_eventid),
    offsetof(Tbox__Net__TboxRemoteDiagnose, eventid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Tbox__Net__TboxRemoteDiagnose, has_timestamp),
    offsetof(Tbox__Net__TboxRemoteDiagnose, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "datatype",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Tbox__Net__TboxRemoteDiagnose, has_datatype),
    offsetof(Tbox__Net__TboxRemoteDiagnose, datatype),
    &tbox__net__data_type_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cameraname",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Tbox__Net__TboxRemoteDiagnose, has_cameraname),
    offsetof(Tbox__Net__TboxRemoteDiagnose, cameraname),
    &tbox__net__camera_name_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aid",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Tbox__Net__TboxRemoteDiagnose, has_aid),
    offsetof(Tbox__Net__TboxRemoteDiagnose, aid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mid",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Tbox__Net__TboxRemoteDiagnose, has_mid),
    offsetof(Tbox__Net__TboxRemoteDiagnose, mid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "effectivetime",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Tbox__Net__TboxRemoteDiagnose, has_effectivetime),
    offsetof(Tbox__Net__TboxRemoteDiagnose, effectivetime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sizelimit",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Tbox__Net__TboxRemoteDiagnose, has_sizelimit),
    offsetof(Tbox__Net__TboxRemoteDiagnose, sizelimit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__tbox_remote_diagnose__field_indices_by_name[] = {
  5,   /* field[5] = aid */
  4,   /* field[4] = cameraname */
  3,   /* field[3] = datatype */
  7,   /* field[7] = effectivetime */
  1,   /* field[1] = eventid */
  6,   /* field[6] = mid */
  8,   /* field[8] = sizelimit */
  2,   /* field[2] = timestamp */
  0,   /* field[0] = vin */
};
static const ProtobufCIntRange tbox__net__tbox_remote_diagnose__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor tbox__net__tbox_remote_diagnose__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.TboxRemoteDiagnose",
  "TboxRemoteDiagnose",
  "Tbox__Net__TboxRemoteDiagnose",
  "tbox.net",
  sizeof(Tbox__Net__TboxRemoteDiagnose),
  9,
  tbox__net__tbox_remote_diagnose__field_descriptors,
  tbox__net__tbox_remote_diagnose__field_indices_by_name,
  1,  tbox__net__tbox_remote_diagnose__number_ranges,
  (ProtobufCMessageInit) tbox__net__tbox_remote_diagnose__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__msg_result__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Tbox__Net__MsgResult, has_result),
    offsetof(Tbox__Net__MsgResult, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_code",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Tbox__Net__MsgResult, has_error_code),
    offsetof(Tbox__Net__MsgResult, error_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__msg_result__field_indices_by_name[] = {
  1,   /* field[1] = error_code */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange tbox__net__msg_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tbox__net__msg_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.MsgResult",
  "MsgResult",
  "Tbox__Net__MsgResult",
  "tbox.net",
  sizeof(Tbox__Net__MsgResult),
  2,
  tbox__net__msg_result__field_descriptors,
  tbox__net__msg_result__field_indices_by_name,
  1,  tbox__net__msg_result__number_ranges,
  (ProtobufCMessageInit) tbox__net__msg_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tbox__net__top_message__field_descriptors[13] =
{
  {
    "message_type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Tbox__Net__TopMessage, has_message_type),
    offsetof(Tbox__Net__TopMessage, message_type),
    &tbox__net__messagetype__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signal_type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Tbox__Net__TopMessage, has_signal_type),
    offsetof(Tbox__Net__TopMessage, signal_type),
    &tbox__net__signal_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signal_power",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Tbox__Net__TopMessage, has_signal_power),
    offsetof(Tbox__Net__TopMessage, signal_power),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tbox_network_ctrl",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, tbox_network_ctrl),
    &tbox__net__tbox_network_ctrl__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call_action",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, call_action),
    &tbox__net__call_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call_status",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, call_status),
    &tbox__net__call_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call_result",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, call_result),
    &tbox__net__call_action_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tbox_info",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, tbox_info),
    &tbox__net__tbox_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tbox_gps_ctrl",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, tbox_gps_ctrl),
    &tbox__net__tbox_gpscmd__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tbox_gpsinfo",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, tbox_gpsinfo),
    &tbox__net__tbox_gpsinfo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tbox_activestate",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, tbox_activestate),
    &tbox__net__tbox_active_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tbox_remotedaignose",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, tbox_remotedaignose),
    &tbox__net__tbox_remote_diagnose__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg_result",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tbox__Net__TopMessage, msg_result),
    &tbox__net__msg_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tbox__net__top_message__field_indices_by_name[] = {
  4,   /* field[4] = call_action */
  6,   /* field[6] = call_result */
  5,   /* field[5] = call_status */
  0,   /* field[0] = message_type */
  12,   /* field[12] = msg_result */
  2,   /* field[2] = signal_power */
  1,   /* field[1] = signal_type */
  10,   /* field[10] = tbox_activestate */
  8,   /* field[8] = tbox_gps_ctrl */
  9,   /* field[9] = tbox_gpsinfo */
  7,   /* field[7] = tbox_info */
  3,   /* field[3] = tbox_network_ctrl */
  11,   /* field[11] = tbox_remotedaignose */
};
static const ProtobufCIntRange tbox__net__top_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor tbox__net__top_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tbox.net.TopMessage",
  "TopMessage",
  "Tbox__Net__TopMessage",
  "tbox.net",
  sizeof(Tbox__Net__TopMessage),
  13,
  tbox__net__top_message__field_descriptors,
  tbox__net__top_message__field_indices_by_name,
  1,  tbox__net__top_message__number_ranges,
  (ProtobufCMessageInit) tbox__net__top_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue tbox__net__messagetype__enum_values_by_number[16] =
{
  { "REQUEST_RESPONSE_NONE", "TBOX__NET__MESSAGETYPE__REQUEST_RESPONSE_NONE", 0 },
  { "REQUEST_HEARTBEAT_SIGNAL", "TBOX__NET__MESSAGETYPE__REQUEST_HEARTBEAT_SIGNAL", 1 },
  { "RESPONSE_HEARTBEAT_RESULT", "TBOX__NET__MESSAGETYPE__RESPONSE_HEARTBEAT_RESULT", 2 },
  { "REQUEST_NETWORK_SIGNAL_STRENGTH", "TBOX__NET__MESSAGETYPE__REQUEST_NETWORK_SIGNAL_STRENGTH", 3 },
  { "RESPONSE_NETWORK_SIGNAL_STRENGTH", "TBOX__NET__MESSAGETYPE__RESPONSE_NETWORK_SIGNAL_STRENGTH", 4 },
  { "REQUEST_CALL_ACTION", "TBOX__NET__MESSAGETYPE__REQUEST_CALL_ACTION", 5 },
  { "RESPONSE_CALL_ACTION_RESULT", "TBOX__NET__MESSAGETYPE__RESPONSE_CALL_ACTION_RESULT", 6 },
  { "RESPONSE_CALL_STATUS", "TBOX__NET__MESSAGETYPE__RESPONSE_CALL_STATUS", 7 },
  { "REQUEST_TBOX_INFO", "TBOX__NET__MESSAGETYPE__REQUEST_TBOX_INFO", 8 },
  { "RESPONSE_TBOX_INFO", "TBOX__NET__MESSAGETYPE__RESPONSE_TBOX_INFO", 9 },
  { "REQUEST_TBOX_GPS_SET", "TBOX__NET__MESSAGETYPE__REQUEST_TBOX_GPS_SET", 10 },
  { "RESPONSE_TBOX_GPS_SET_RESULT", "TBOX__NET__MESSAGETYPE__RESPONSE_TBOX_GPS_SET_RESULT", 11 },
  { "RESPONSE_TBOX_GPSINFO_RESULT", "TBOX__NET__MESSAGETYPE__RESPONSE_TBOX_GPSINFO_RESULT", 12 },
  { "RESPONSE_TBOX_ACTIVESTATE_RESULT", "TBOX__NET__MESSAGETYPE__RESPONSE_TBOX_ACTIVESTATE_RESULT", 13 },
  { "REQUEST_TBOX_REMOTEDIAGNOSE", "TBOX__NET__MESSAGETYPE__REQUEST_TBOX_REMOTEDIAGNOSE", 14 },
  { "RESPONSE_TBOX_REMOTEDIAGNOSE_RESULT", "TBOX__NET__MESSAGETYPE__RESPONSE_TBOX_REMOTEDIAGNOSE_RESULT", 15 },
};
static const ProtobufCIntRange tbox__net__messagetype__value_ranges[] = {
{0, 0},{0, 16}
};
static const ProtobufCEnumValueIndex tbox__net__messagetype__enum_values_by_name[16] =
{
  { "REQUEST_CALL_ACTION", 5 },
  { "REQUEST_HEARTBEAT_SIGNAL", 1 },
  { "REQUEST_NETWORK_SIGNAL_STRENGTH", 3 },
  { "REQUEST_RESPONSE_NONE", 0 },
  { "REQUEST_TBOX_GPS_SET", 10 },
  { "REQUEST_TBOX_INFO", 8 },
  { "REQUEST_TBOX_REMOTEDIAGNOSE", 14 },
  { "RESPONSE_CALL_ACTION_RESULT", 6 },
  { "RESPONSE_CALL_STATUS", 7 },
  { "RESPONSE_HEARTBEAT_RESULT", 2 },
  { "RESPONSE_NETWORK_SIGNAL_STRENGTH", 4 },
  { "RESPONSE_TBOX_ACTIVESTATE_RESULT", 13 },
  { "RESPONSE_TBOX_GPSINFO_RESULT", 12 },
  { "RESPONSE_TBOX_GPS_SET_RESULT", 11 },
  { "RESPONSE_TBOX_INFO", 9 },
  { "RESPONSE_TBOX_REMOTEDIAGNOSE_RESULT", 15 },
};
const ProtobufCEnumDescriptor tbox__net__messagetype__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.Messagetype",
  "Messagetype",
  "Tbox__Net__Messagetype",
  "tbox.net",
  16,
  tbox__net__messagetype__enum_values_by_number,
  16,
  tbox__net__messagetype__enum_values_by_name,
  1,
  tbox__net__messagetype__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__network__send__on_off__enum_values_by_number[3] =
{
  { "NETWORK_ON", "TBOX__NET__NETWORK__SEND__ON_OFF__NETWORK_ON", 0 },
  { "NETWORK_OFF", "TBOX__NET__NETWORK__SEND__ON_OFF__NETWORK_OFF", 1 },
  { "NETWORK_ONCE", "TBOX__NET__NETWORK__SEND__ON_OFF__NETWORK_ONCE", 2 },
};
static const ProtobufCIntRange tbox__net__network__send__on_off__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex tbox__net__network__send__on_off__enum_values_by_name[3] =
{
  { "NETWORK_OFF", 1 },
  { "NETWORK_ON", 0 },
  { "NETWORK_ONCE", 2 },
};
const ProtobufCEnumDescriptor tbox__net__network__send__on_off__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.NETWORK_SEND_OnOff",
  "NETWORK_SEND_OnOff",
  "Tbox__Net__NETWORKSENDOnOff",
  "tbox.net",
  3,
  tbox__net__network__send__on_off__enum_values_by_number,
  3,
  tbox__net__network__send__on_off__enum_values_by_name,
  1,
  tbox__net__network__send__on_off__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__signal_type__enum_values_by_number[4] =
{
  { "NONE_SIGNAL", "TBOX__NET__SIGNAL_TYPE__NONE_SIGNAL", 0 },
  { "GSM", "TBOX__NET__SIGNAL_TYPE__GSM", 1 },
  { "UMTS", "TBOX__NET__SIGNAL_TYPE__UMTS", 2 },
  { "LTE", "TBOX__NET__SIGNAL_TYPE__LTE", 3 },
};
static const ProtobufCIntRange tbox__net__signal_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex tbox__net__signal_type__enum_values_by_name[4] =
{
  { "GSM", 1 },
  { "LTE", 3 },
  { "NONE_SIGNAL", 0 },
  { "UMTS", 2 },
};
const ProtobufCEnumDescriptor tbox__net__signal_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.SignalType",
  "SignalType",
  "Tbox__Net__SignalType",
  "tbox.net",
  4,
  tbox__net__signal_type__enum_values_by_number,
  4,
  tbox__net__signal_type__enum_values_by_name,
  1,
  tbox__net__signal_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__call_type__enum_values_by_number[3] =
{
  { "ECALL", "TBOX__NET__CALL_TYPE__ECALL", 0 },
  { "BCALL", "TBOX__NET__CALL_TYPE__BCALL", 1 },
  { "ICALL", "TBOX__NET__CALL_TYPE__ICALL", 2 },
};
static const ProtobufCIntRange tbox__net__call_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex tbox__net__call_type__enum_values_by_name[3] =
{
  { "BCALL", 1 },
  { "ECALL", 0 },
  { "ICALL", 2 },
};
const ProtobufCEnumDescriptor tbox__net__call_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.CallType",
  "CallType",
  "Tbox__Net__CallType",
  "tbox.net",
  3,
  tbox__net__call_type__enum_values_by_number,
  3,
  tbox__net__call_type__enum_values_by_name,
  1,
  tbox__net__call_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__call_action_enum__enum_values_by_number[2] =
{
  { "START_CALL", "TBOX__NET__CALL_ACTION_ENUM__START_CALL", 0 },
  { "END_CALL", "TBOX__NET__CALL_ACTION_ENUM__END_CALL", 1 },
};
static const ProtobufCIntRange tbox__net__call_action_enum__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex tbox__net__call_action_enum__enum_values_by_name[2] =
{
  { "END_CALL", 1 },
  { "START_CALL", 0 },
};
const ProtobufCEnumDescriptor tbox__net__call_action_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.CallActionEnum",
  "CallActionEnum",
  "Tbox__Net__CallActionEnum",
  "tbox.net",
  2,
  tbox__net__call_action_enum__enum_values_by_number,
  2,
  tbox__net__call_action_enum__enum_values_by_name,
  1,
  tbox__net__call_action_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__call_action_result_enum__enum_values_by_number[6] =
{
  { "CALL_ACTION_SUCCESS", "TBOX__NET__CALL_ACTION_RESULT_ENUM__CALL_ACTION_SUCCESS", 0 },
  { "CALL_ACTION_NONSUPPORT", "TBOX__NET__CALL_ACTION_RESULT_ENUM__CALL_ACTION_NONSUPPORT", 1 },
  { "START_FAILED_CALL_PROCESSING", "TBOX__NET__CALL_ACTION_RESULT_ENUM__START_FAILED_CALL_PROCESSING", 2 },
  { "START_FAILED_OTHER_ERROR", "TBOX__NET__CALL_ACTION_RESULT_ENUM__START_FAILED_OTHER_ERROR", 3 },
  { "END_FAILED_NO_CURRENT_CALL", "TBOX__NET__CALL_ACTION_RESULT_ENUM__END_FAILED_NO_CURRENT_CALL", 4 },
  { "END_FAILED_OTHER_ERROR", "TBOX__NET__CALL_ACTION_RESULT_ENUM__END_FAILED_OTHER_ERROR", 5 },
};
static const ProtobufCIntRange tbox__net__call_action_result_enum__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex tbox__net__call_action_result_enum__enum_values_by_name[6] =
{
  { "CALL_ACTION_NONSUPPORT", 1 },
  { "CALL_ACTION_SUCCESS", 0 },
  { "END_FAILED_NO_CURRENT_CALL", 4 },
  { "END_FAILED_OTHER_ERROR", 5 },
  { "START_FAILED_CALL_PROCESSING", 2 },
  { "START_FAILED_OTHER_ERROR", 3 },
};
const ProtobufCEnumDescriptor tbox__net__call_action_result_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.CallActionResultEnum",
  "CallActionResultEnum",
  "Tbox__Net__CallActionResultEnum",
  "tbox.net",
  6,
  tbox__net__call_action_result_enum__enum_values_by_number,
  6,
  tbox__net__call_action_result_enum__enum_values_by_name,
  1,
  tbox__net__call_action_result_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__call_status_enum__enum_values_by_number[5] =
{
  { "CALL_IN", "TBOX__NET__CALL_STATUS_ENUM__CALL_IN", 0 },
  { "CALL_OUT", "TBOX__NET__CALL_STATUS_ENUM__CALL_OUT", 1 },
  { "CALL_RING", "TBOX__NET__CALL_STATUS_ENUM__CALL_RING", 2 },
  { "CALL_CONNECTED", "TBOX__NET__CALL_STATUS_ENUM__CALL_CONNECTED", 3 },
  { "CALL_DISCONNECTED", "TBOX__NET__CALL_STATUS_ENUM__CALL_DISCONNECTED", 4 },
};
static const ProtobufCIntRange tbox__net__call_status_enum__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex tbox__net__call_status_enum__enum_values_by_name[5] =
{
  { "CALL_CONNECTED", 3 },
  { "CALL_DISCONNECTED", 4 },
  { "CALL_IN", 0 },
  { "CALL_OUT", 1 },
  { "CALL_RING", 2 },
};
const ProtobufCEnumDescriptor tbox__net__call_status_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.CallStatusEnum",
  "CallStatusEnum",
  "Tbox__Net__CallStatusEnum",
  "tbox.net",
  5,
  tbox__net__call_status_enum__enum_values_by_number,
  5,
  tbox__net__call_status_enum__enum_values_by_name,
  1,
  tbox__net__call_status_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__gps__send__on_off__enum_values_by_number[3] =
{
  { "GPS_ON", "TBOX__NET__GPS__SEND__ON_OFF__GPS_ON", 0 },
  { "GPS_OFF", "TBOX__NET__GPS__SEND__ON_OFF__GPS_OFF", 1 },
  { "GPS_ONCE", "TBOX__NET__GPS__SEND__ON_OFF__GPS_ONCE", 2 },
};
static const ProtobufCIntRange tbox__net__gps__send__on_off__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex tbox__net__gps__send__on_off__enum_values_by_name[3] =
{
  { "GPS_OFF", 1 },
  { "GPS_ON", 0 },
  { "GPS_ONCE", 2 },
};
const ProtobufCEnumDescriptor tbox__net__gps__send__on_off__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.GPS_SEND_OnOff",
  "GPS_SEND_OnOff",
  "Tbox__Net__GPSSENDOnOff",
  "tbox.net",
  3,
  tbox__net__gps__send__on_off__enum_values_by_number,
  3,
  tbox__net__gps__send__on_off__enum_values_by_name,
  1,
  tbox__net__gps__send__on_off__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__data_type_enum__enum_values_by_number[2] =
{
  { "PHOTO_TYPE", "TBOX__NET__DATA_TYPE_ENUM__PHOTO_TYPE", 0 },
  { "VIDEO_TYPE", "TBOX__NET__DATA_TYPE_ENUM__VIDEO_TYPE", 1 },
};
static const ProtobufCIntRange tbox__net__data_type_enum__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex tbox__net__data_type_enum__enum_values_by_name[2] =
{
  { "PHOTO_TYPE", 0 },
  { "VIDEO_TYPE", 1 },
};
const ProtobufCEnumDescriptor tbox__net__data_type_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.DataTypeEnum",
  "DataTypeEnum",
  "Tbox__Net__DataTypeEnum",
  "tbox.net",
  2,
  tbox__net__data_type_enum__enum_values_by_number,
  2,
  tbox__net__data_type_enum__enum_values_by_name,
  1,
  tbox__net__data_type_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tbox__net__camera_name_enum__enum_values_by_number[2] =
{
  { "DVR_TYPE", "TBOX__NET__CAMERA_NAME_ENUM__DVR_TYPE", 0 },
  { "DMS_TYPE", "TBOX__NET__CAMERA_NAME_ENUM__DMS_TYPE", 1 },
};
static const ProtobufCIntRange tbox__net__camera_name_enum__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex tbox__net__camera_name_enum__enum_values_by_name[2] =
{
  { "DMS_TYPE", 1 },
  { "DVR_TYPE", 0 },
};
const ProtobufCEnumDescriptor tbox__net__camera_name_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tbox.net.CameraNameEnum",
  "CameraNameEnum",
  "Tbox__Net__CameraNameEnum",
  "tbox.net",
  2,
  tbox__net__camera_name_enum__enum_values_by_number,
  2,
  tbox__net__camera_name_enum__enum_values_by_name,
  1,
  tbox__net__camera_name_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
