/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -S skeletons -fskeletons-copy -fnative-types -gen-PER`
 */

#include <asn_internal.h>

#include "Appdatainfo.h"

static asn_TYPE_member_t asn_MBR_Appdatainfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Appdatainfo, choice.xcallReq),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_XcallReqinfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"xcallReq"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Appdatainfo, choice.xcallResp),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_XcallRespinfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"xcallResp"
		},
};
static asn_TYPE_tag2member_t asn_MAP_Appdatainfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* xcallReq at 41 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* xcallResp at 43 */
};
static asn_CHOICE_specifics_t asn_SPC_Appdatainfo_specs_1 = {
	sizeof(struct Appdatainfo),
	offsetof(struct Appdatainfo, _asn_ctx),
	offsetof(struct Appdatainfo, present),
	sizeof(((struct Appdatainfo *)0)->present),
	asn_MAP_Appdatainfo_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static asn_per_constraints_t asn_PER_Appdatainfo_constr_1 = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
asn_TYPE_descriptor_t asn_DEF_Appdatainfo = {
	"Appdatainfo",
	"Appdatainfo",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_Appdatainfo_constr_1,
	asn_MBR_Appdatainfo_1,
	2,	/* Elements count */
	&asn_SPC_Appdatainfo_specs_1	/* Additional specs */
};

