/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -S skeletons -fskeletons-copy -fnative-types -gen-PER`
 */

#ifndef	_Appdatainfo_H_
#define	_Appdatainfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "XcallReqinfo.h"
#include "XcallRespinfo.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Appdatainfo_PR {
	Appdatainfo_PR_NOTHING,	/* No components present */
	Appdatainfo_PR_xcallReq,
	Appdatainfo_PR_xcallResp
} Appdatainfo_PR;

/* Appdatainfo */
typedef struct Appdatainfo {
	Appdatainfo_PR present;
	union Appdatainfo_u {
		XcallReqinfo_t	 xcallReq;
		XcallRespinfo_t	 xcallResp;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Appdatainfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Appdatainfo;

#ifdef __cplusplus
}
#endif

#endif	/* _Appdatainfo_H_ */
