/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#include "CfgGetRespInfo.h"

static int
memb_ficmCfg_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size <= 1)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_ficmCfg_constr_3 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (SIZE(0..1)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ficmCfg_constr_3 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (SIZE(0..1)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ficmCfg_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_FICMConfigSettings,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ficmCfg_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ficmCfg_specs_3 = {
	sizeof(struct ficmCfg),
	offsetof(struct ficmCfg, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ficmCfg_3 = {
	"ficmCfg",
	"ficmCfg",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ficmCfg_tags_3,
	sizeof(asn_DEF_ficmCfg_tags_3)
		/sizeof(asn_DEF_ficmCfg_tags_3[0]) - 1, /* 1 */
	asn_DEF_ficmCfg_tags_3,	/* Same as above */
	sizeof(asn_DEF_ficmCfg_tags_3)
		/sizeof(asn_DEF_ficmCfg_tags_3[0]), /* 2 */
	&asn_PER_type_ficmCfg_constr_3,
	asn_MBR_ficmCfg_3,
	1,	/* Single element */
	&asn_SPC_ficmCfg_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CfgGetRespInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CfgGetRespInfo, result),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"result"
		},
	{ ATF_POINTER, 1, offsetof(struct CfgGetRespInfo, ficmCfg),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_ficmCfg_3,
		memb_ficmCfg_constraint_1,
		&asn_PER_memb_ficmCfg_constr_3,
		0,
		"ficmCfg"
		},
};
static const int asn_MAP_CfgGetRespInfo_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_CfgGetRespInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CfgGetRespInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* result */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ficmCfg */
};
static asn_SEQUENCE_specifics_t asn_SPC_CfgGetRespInfo_specs_1 = {
	sizeof(struct CfgGetRespInfo),
	offsetof(struct CfgGetRespInfo, _asn_ctx),
	asn_MAP_CfgGetRespInfo_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_CfgGetRespInfo_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CfgGetRespInfo = {
	"CfgGetRespInfo",
	"CfgGetRespInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CfgGetRespInfo_tags_1,
	sizeof(asn_DEF_CfgGetRespInfo_tags_1)
		/sizeof(asn_DEF_CfgGetRespInfo_tags_1[0]), /* 1 */
	asn_DEF_CfgGetRespInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_CfgGetRespInfo_tags_1)
		/sizeof(asn_DEF_CfgGetRespInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CfgGetRespInfo_1,
	2,	/* Elements count */
	&asn_SPC_CfgGetRespInfo_specs_1	/* Additional specs */
};

