/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -S skeletons -fskeletons-copy -fnative-types -gen-PER`
 */

#ifndef	_Headinfo_H_
#define	_Headinfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <IA5String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Headinfo */
typedef struct Headinfo {
	long	 protocolVer;
	long	 disMsgLen;
	long	 disBodyEncode;
	long	 tboxIdType;
	IA5String_t	*tboxid	/* OPTIONAL */;
	IA5String_t	*tboxsn	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Headinfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Headinfo;

#ifdef __cplusplus
}
#endif

#endif	/* _Headinfo_H_ */
