/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -S skeletons -fskeletons-copy -fnative-types -gen-PER`
 */

#include <asn_internal.h>

#include "MessageData.h"

static asn_TYPE_member_t asn_MBR_MessageData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MessageData, disHeader),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Headinfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"disHeader"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MessageData, disBody),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Bodyinfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"disBody"
		},
	{ ATF_POINTER, 1, offsetof(struct MessageData, appdata),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Appdatainfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"appdata"
		},
};
static int asn_MAP_MessageData_oms_1[] = { 2 };
static ber_tlv_tag_t asn_DEF_MessageData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_MessageData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* disHeader at 7 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* disBody at 8 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* appdata at 9 */
};
static asn_SEQUENCE_specifics_t asn_SPC_MessageData_specs_1 = {
	sizeof(struct MessageData),
	offsetof(struct MessageData, _asn_ctx),
	asn_MAP_MessageData_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_MessageData_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MessageData = {
	"MessageData",
	"MessageData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MessageData_tags_1,
	sizeof(asn_DEF_MessageData_tags_1)
		/sizeof(asn_DEF_MessageData_tags_1[0]), /* 1 */
	asn_DEF_MessageData_tags_1,	/* Same as above */
	sizeof(asn_DEF_MessageData_tags_1)
		/sizeof(asn_DEF_MessageData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MessageData_1,
	3,	/* Elements count */
	&asn_SPC_MessageData_specs_1	/* Additional specs */
};

