/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -S skeletons -fskeletons-copy -fnative-types -gen-PER`
 */

#ifndef	_MessageData_H_
#define	_MessageData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Headinfo.h"
#include "Bodyinfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Appdatainfo;

/* MessageData */
typedef struct MessageData {
	Headinfo_t	 disHeader;
	Bodyinfo_t	 disBody;
	struct Appdatainfo	*appdata	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MessageData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Appdatainfo.h"

#endif	/* _MessageData_H_ */
