/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_MessageData;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module HOZON in HOZON_PRIV_v1.0.asn */
	&asn_DEF_MessageData,	
	0
};

