/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -S skeletons -fskeletons-copy -fnative-types -gen-PER`
 */

#ifndef	_XcallRespinfo_H_
#define	_XcallRespinfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "RvsposInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* XcallRespinfo */
typedef struct XcallRespinfo {
	long	 xcallType;
	long	 engineSt;
	long	 ttOdoMeter;
	RvsposInfo_t	 gpsPos;
	long	 srsSt;
	long	 updataTime;
	long	 battSOCEx;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} XcallRespinfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_XcallRespinfo;

#ifdef __cplusplus
}
#endif

#endif	/* _XcallRespinfo_H_ */
